#!/bin/bash

# Run in TDBROOT

TDBROOT="${TDBROOT:-$HOME/Projects/TDB}"
DATASETS="${DATASETS:-$HOME/Datasets}"
#DB_DESC="$TDBROOT/DB/DBpediaBM/dataset-dbp.ttl"
LOCATION="--location DB"
PARA="${PARA:---parallel}"

tdbclean "$LOCATION"
tdbloader $LOCATION $PARA \
    $DATASETS/DBPediaBM/dbp-infoboxes.nt \
    $DATASETS/DBPediaBM/dbp-geocoordinates.nt \
    $DATASETS/DBPedia/dbp-homepages.nt \
    | tee LOG
