#!/bin/bash

# Run in TDBROOT

TDBROOT="${TDBROOT:-$HOME/Projects/AFS}"

DATASETS="${DATASETS:-$HOME/Datasets}"

#DB_DESC="$TDBROOT/DB/DBpediaBM/dataset.ttl"

TARGET=tmp
PARA="${PARA:---parallel}"

tdbclean "$TARGET"
tdbloader --location "$TARGET" $PARA \
    $DATASETS/DBpedia/dbp-infoboxes.nt \
    $DATASETS/DBpedia/dbp-geocoordinates.nt \
    $DATASETS/DBpedia/dbp-homepages.nt \
    | tee LOG
