#!/bin/bash

# Run in TDBROOT
TDBROOT="${TDBROOT:-$HOME/Projects/TDB}"
DB_DIR=DB
LOCATION="--location $DB_DIR"
#DB_DESC="$TDBROOT/DB/dataset-dbp.ttl"
# "none" does consume all nodes.
RESULTS=none

for q in $TDBROOT/Perf/DBpedia-1/query?.rq
do
  N=$(basename "$q")
  echo "==== $N ===="
  tdbquery --time --results $RESULTS $LOCATION --query "$q"
  done

for q in $TDBROOT/Perf/DBpedia-1/query?a.rq
do
  N="$(basename $q)"
  echo "==== $N ===="
  tdbquery --time --results $RESULTS $LOCATION --query "$q"
  done
