#!/bin/bash

# Run in TDBROOT
TDBROOT="${TDBROOT:-$HOME/Projects/AFS}"
DB_DESC="$TDBROOT/DB/dataset-dbp.ttl"

RESULTS=none

for q in $TDBROOT/Perf/DBpedia-1/query?.rq
do
  N=$(basename "$q")
  echo "==== $N ===="
  tdbquery --time --results $RESULTS --desc "$DB_DESC" --query "$q"
  done

for q in $TDBROOT/Perf/DBpedia-1/query?a.rq
do
  N="$(basename $q)"
  echo "==== $N ===="
  tdbquery --time --results $RESULTS --desc "$DB_DESC" --query "$q"
  done
