PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?s ?homepage WHERE {
	<http://dbpedia.org/resource/Berlin> geo:lat ?berlinLat .
	?s geo:lat ?lat .

	<http://dbpedia.org/resource/Berlin> geo:long ?berlinLong .	
	?s geo:long ?long .
	?s foaf:homepage ?homepage .
FILTER ( ?lat        <=      ?berlinLat + 0.03190235436 )
FILTER ( ?long         >=      ?berlinLong - 0.08679199218 )
FILTER ( ?lat        >=     ?berlinLat - 0.03190235436 )
FILTER ( ?long         <=      ?berlinLong + 0.08679199218)
}
