# Example 2 from
# http://lists.w3.org/Archives/Public/public-rdf-dawg/2005JulSep/0096
# $Id: normalization-03.rq,v 1.1 2005/10/25 17:26:57 andy_seaborne Exp $
PREFIX : <http://example/vocab#>
PREFIX p2: <http://example.com:80/#>

SELECT ?S WHERE { ?S :p p2:abc }

