#!/usr/bin/perl
# Write a run script.




$POM="pom.xml" ;
$POM = @ARGV[0] if ( defined(@ARGV[0]) ) ;

if ( ! -e "$POM" )
{
    print STDERR "No POM file: $POM\n" ;
    exit 1 ;
}

print "#!/bin/bash\n" ;
print 'M2_REPO="${M2_REPO:-$HOME/.m2/repository}"' ;
print "\n" ;
print "\n" ;
print 'CP="' ;
$first = 1 ;

open(X, "mvn -f $POM dependency:build-classpath |") ;
while(<X>)
{
    next if /\[INFO\]/ ;
    chop ;
    print "$_" ;
}
## open(X, "mvn dependency:list|") ;
## 
## while(<X>)
## {
##     next unless /:compile/ ;
##     ($g,$a,$v) = m/(\S*):(.*):jar:(.*):compile/ ;
##     $g =~ s!\.!/!g ;
##     print ":" if ( ! $first ) ;
##     print "\$M2_REPO/$g/$a/$v/$a-$v.jar" ;
##     $first = 0 ;
## }
print "\"\n" ;
print "\n" ;
print "echo \"\$CP\"\n"

