## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

## See https://s.apache.org/asfyaml

notifications:
    commits:       commits@jena.apache.org
    issues:        pr@jena.apache.org
    pullrequests:  pr@jena.apache.org
    jira_options:  link label

github:
  description: "Apache Jena"
  homepage: https://jena.apache.org/
  protected_branches:
    main
  labels:
    - apache
    - jena
    - rdf
    - sparql

