#!/usr/bin/perl
# Remove old head/tail /*...*/ comments and add apache boilerplate.
# find DIRS -name \*.java -o -name .svn -prune | xargs perl perl-script

# TODO Remove only last /*..*/ comment, not all the ones after last }

&setExclude ;
undef $/ ;

while(defined($file = shift @ARGV))
{
    # Excludes
    next if ( defined($exclude{$file}) ) ;
    &process($file) ;
}

sub process
{
    my $file = @_[0] ;
    open(FILE, "<$file") || die ;
    binmode FILE ;
    $_ = <FILE> ;
    my $t = &clean($_) ;
    print $t ;
    print "\n" ;
}

## head and tail
sub clean
{
    my $text = @_[0] ;
    $text =~ s!^\s*/\*[^{}/]*\*/\s*!!s ;
    # This removes all trailing comments, not just the last.
    $text =~ s!\s*/\*[^{}]*\*/\s*$!!s ;
    # No newline on end.
    return $text ;
}

##     # Head
##     if ( m!^\s*/\*[^{}]*\*/!s )
##     {
## 	##print "HEAD\n" ;
## 	$head = $& ;
## 	##print $head,"\n" ;
## 	##print "HEAD\n" ;
##     }
##     if ( m!/\*[^{}]*\*/\s*$!s )
##     {
## 	##print "TAIL\n" ;
## 	$tail = $& ;
## 	##print $tail,"\n" ;
## 	##print "TAIL\n" ;
##     }

sub setExclude
{
}
