#!/usr/bin/perl
# Remove old head/tail /*...*/ comments and add apache boilerplate.
# find DIRS -name \*.java -o -name .svn -prune | xargs perl perl-script

# TODO Remove only last /*..*/ comment, not all the ones after last }

&setExclude ;
undef $/ ;

$HTEXT="HEADER" ;
$TTEXT="TRAILER" ;

while(defined($file = shift @ARGV))
{
    # Excludes
    next if ( defined($exclude{$file}) ) ;
    &process($file) ;
}

sub process
{
    my $file = @_[0] ;
    open(FILE, "<$file") || die ;
    binmode FILE ;
    $_ = <FILE> ;
    my $t = &clean($_) ;
    print $HTEXT,"\n" ;
    print $t ;
    print "\n" unless ( $t =~ /\n$/s ) ;
    print $TTEXT,"\n" ;
}

## head and tail
sub clean
{
    my $text = @_[0] ;
    ## These remove multipl adjacent comments
    # remove first comment

##     $text =~ s!^\s*/\*[^{}/]*\*/\s*!!s ;
##     $text =~ s!\s*/\*[^{}]*\*/\s*$!!s ;

    $text =~ s!^ ## Start of file.
\s*               ## Whitespace
/\*               ## Start of comment
[^*]*\*+          ## Any non-* then 1-or-more *
([^/][^*]*\*+)*   ## Repeats of not-/ then unit as above
/                 ## Close / for the comment
\s*               ## Whitespace
!!sx ;

    # Blocks *(not/)-starting text
    $text =~ s!
\s*               ## Whitespace
/\*               ## Start of comment
[^*]*\*+          ## Any non-* then 1-or-more *
([^/][^*]*\*+)*   ## Repeats of not-/ then unit as above
/                 ## Close / for the comment
\s*$              ## Whitespace, end of file
!!sx ;
    return $text ;
}

##     # Head
##     if ( m!^\s*/\*[^{}]*\*/!s )
##     {
## 	##print "HEAD\n" ;
## 	$head = $& ;
## 	##print $head,"\n" ;
## 	##print "HEAD\n" ;
##     }
##     if ( m!/\*[^{}]*\*/\s*$!s )
##     {
## 	##print "TAIL\n" ;
## 	$tail = $& ;
## 	##print $tail,"\n" ;
## 	##print "TAIL\n" ;
##     }

sub setExclude
{
}
