#!/usr/bin/perl
# Convert copyright notices to Apache style.
# Remove old head/tail /*...*/ comments and add apache boilerplate.
# Not perfect (string with "/*" or "*/" in them may fool it) but it does
# the bulk conversion to leave one or two cases.

# find DIRS -name \*.java -print -o -name .svn -prune | xargs -n 1 perl -i.bak perl-script
# find src* -name \*.java -print -o -name .svn -prune |  xargs -n 1 perl -i.bak ../JenaTop/apacheize

$HTEXT= <<'END';
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
END

$TTEXT="" ;

undef $/ ;
$text = <> ;
## # Protect // /* and " /*
## $text =~ s!//(.*)/\*!//$1/-XYXY-!g ;
## $text =~ s!//(.*)"\*!//$1"-XYXY-!g ;

## These remove multiple adjacent comments
# remove first comment

$text =~ s!^ ## Start of file.
\s*               ## Whitespace
/\*               ## Start of comment
[^*]*\*+          ## Any non-* then 1-or-more *
([^/][^*]*\*+)*   ## Repeats of not-/ then unit as above
/                 ## Close / for the comment
\s*               ## Whitespace
!!sx ;

# Blocks *(not/)-starting text
# Includes trailing } to anchor things.
# Assumes no {} in the final /* comment block
#  Indeed, "}[^}*]$" is probably enough without training comments.

$text =~ s!
}[^}]*            ## End of class - anchors expression. {} do not appear in (c)
/\*               ## Start of comment
[^*{}]*\*+          ## Any non-* then 1-or-more *
([^/{}][^*{}]*\*+)*   ## Repeats of not-/ then unit as above
/                 ## Close / for the comment
\s*$              ## Whitespace, end of file
!}\n!sx ;

$text = trim($text) ;
$text =~ s!-XYXY-!\*!g ;

print $HTEXT,"\n" ;
print $text ;
print "\n" unless ( $text =~ /\n$/s ) ;
print $TTEXT,"\n" if ( $TTEXT ne "" ) ;

# Perl trim function to remove whitespace from the start and end of the string
sub trim($)
{
	my $string = shift;
	$string =~ s/^\s+//;
	$string =~ s/\s+$//;
	return $string;
}
