#!/bin/bash

if [ "$TDBROOT" = "" ]
then
    echo "TDBROOT is not set" 1>&2
    exit 1
    fi

M2_REPO="/home/afs/.m2/repo" ;
X=$(perl -ne 'next unless /kind="var"\s*path="M2_REPO([^"]*)"/ ; print "$1","\n"' .classpath)

CP=
for x in $X
do
   CP="$CP:$M2_REPO$x"
done
CP="classes$CP"

exec java -cp "$CP" -Xmx1200M test.BPlusTreeRun "$@"
