PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :       <http://example/>
PREFIX apf:     <http://jena.hpl.hp.com/ARQ/property#>

SELECT ?x ?m
{ ?x ?p ?bag .
  ?bag a rdf:Seq .
#  ?bag rdfs:member ?m
  ?bag apf:seq ?m
}
