#!/bin/perl
# Update the copyright in ONE file.
# Use on src*/ and doc/
# Avoid javadoc:
# find doc -name \*html | xargs -n 1 perl -i.bak fixCopy
# find src -name \*java | xargs -n 1 perl -i.bak fixCopy

undef $/ ;
$_ = <> ;
s/import com.hp.hpl.jena.sparql.util.IndentedWriter/import org.openjena.atlas.io.IndentedWriter/ ;
s/import com.hp.hpl.jena.sparql.util.IndentedLineBuffer/import org.openjena.atlas.io.IndentedLineBuffer/ ;
print $_ ;
