#!/bin/perl

# Check (and change) source code
# Use with "find src/ -name \*java -print -o -name .svn -prune -o -name CVS -prune | xargs -n 1 perl -i.bak fixCopy"

undef $/ ;
$_ = <> ;

# Move on one year
s!2008(\s+)Hewlett-Packard!2007, 2008, 2009 Hewlett-Packard!g ;

print $_ ;
