#!/bin/bash

export FUSEKI_HOME=${FUSEKI_HOME:-$PWD}

if [ ! -e $FUSEKI_HOME ]
then
    echo "$FUSEKI_HOME does not exist" 1>&2
    exit 1
    fi

JAR1="$FUSEKI_HOME/fuseki-server.jar"
JAR2="$FUSEKI_HOME/jena-fuseki-*-server.jar"
JAR=""

for J in "$JAR1" "$JAR2"
do
    # Expand
    J="$(echo $J)"
    if [ -e "$J" ]
    then
	JAR="$J"
	break
    fi
done

if [ "$JAR" = "" ]
then
    echo "Can't find jarfile to run"
    exit 1
    fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

exec java  $JVM_ARGS -jar "$JAR" "$@"
