#!/bin/bash

JAR1="fuseki-sys.jar"
JAR2="target/fuseki-*-sys.jar"
JAR=""

for J in "$JAR1" "$JAR2"
do
    # Expand
    J="$(echo $J)"
    if [ -e "$J" ]
    then
	JAR="$J"
	break
    fi
done

if [ "$JAR" = "" ]
then
    echo "Can't find jarfile to run"
    exit 1
    fi

exec java -Xmx1200M -jar "$JAR" "$@"
