#!/bin/bash

M2_REPO="/home/afs/.m2/repo" ;
X=$(perl -ne 'next unless /kind="var"\s*path="M2_REPO([^"]*)"/ ; print "$1","\n"' .classpath)

CP=
for x in $X
do
   CP="$CP:$M2_REPO$x"
done
CP="classes$CP"
JVM_ARGS="-Xmx1200M"
JVM_ARGS="$JVM_ARGS -XX:MaxDirectMemorySize:1G"

exec java -cp "$CP" -Xmx1200M org.openjena.fuseki.FusekiCmd "$@"
