#!/bin/bash

if [ "$JRUBY_HOME" = "" ]
then
    echo "JRUBY_HOME not set" 1>&2
    exit 1
    fi

CP="$(bin/sdb_path);jdbc/*;$JRUBY_HOME/lib/jruby.jar"

#exec java -jar "$JRUBY_HOME/lib/jruby.jar" "$@"
exec java -cp "$CP" org.jruby.Main "$@"
