#!/bin/bash

CLASSPATH="$(bin/arq_path)"

if [ "$OSTYPE" = cygwin ]
then
    CLASSPATH="$(cygpath -w -p "$CLASSPATH")"
    fi

if [ "$#" != 1 ]
then
    echo "Usage: $0 file" 1>&2
    exit 1
    fi

java -Xmx1024M -server -cp "$CLASSPATH" perf.Tokens "$@"

