#!/bin/bash

# --data-binary @FILE : POST
# --upload-file PUT

DEST='http://localhost:3030/dataset?graph=foo'

lwp-request -m POST -c 'application/turtle' 'http://localhost:3030/dataset?graph=foo' < D.ttl

lwp-request -m POST -c 'text/plain' 'http://localhost:3030/dataset?default' < D.nt

## lwp-request -m POST -c 'text/plain' 'http://localhost:3030/dataset' < D.nt

## # DELETE
## lwp-request -m DELETE 'http://localhost:3030/dataset?graph=foo'
## 
## # POST
## lwp-request -m POST 'http://localhost:3030/dataset?graph=foo' < D.ttl
## 
## # PUT
## lwp-request -m PUT 'http://localhost:3030/dataset?graph=foo' < D1.ttl
## 
## # GET
## lwp-request -m GET 'http://localhost:3030/dataset?graph=foo'



# curl --data-binary D.ttl "$DEST"
# wget -S --post-file=D.ttl -O- "$DEST