PREFIX  :     <http://example/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?x ?w
{
    ?x :p ?z . 
     OPTIONAL { ?z :q1 ?w }
     OPTIONAL { ?z :q2 ?w }


##     OPTIONAL { ?z :q1 ?w . ?z :q3 ?r}
##     OPTIONAL { ?z :q2 ?w . ?z :q3 ?r}
#    OPTIONAL { ?z :q3 ?w }
}
