#prefix apf: <http://jena.hpl.hp.com/ARQ/property#>
prefix apf: <java:com.hp.hpl.jena.sparql.pfunction.library.>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

select ?s ?l
{
 ?s <http://example/fruits> ?seq .
 ?seq apf:seq ?l .
 #   ?seq rdfs:member ?l .
} ORDER BY ?l
