    PREFIX  xsd:    <http://www.w3.org/2001/XMLSchema#>
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX dct: <http://purl.org/dc/terms/>

    SELECT * WHERE {
        ?resource a skos:Concept .
        ?resource dct:modified ?modified .
    FILTER(xsd:dateTime(?modified) != 1)
    }
##     ORDER BY DESC(?modified)
##     LIMIT 100
