PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX acm: <http://example/acm>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT { ?s ?p ?o }
{
GRAPH ?g {
?s acm:doingBusinessAsName ?v7.
#FILTER (?v7 < '2010-09-01T05:00:00Z'^^xsd:dateTime)
FILTER regex(?v7, "500", "i" )
#FILTER regex(?v7, "600")     ## no "i" - keep in Java
#FILTER regex(?v7, "Doing_Business_01", "i" )
#FILTER regex(?v8, "234", "i" )
#FILTER regex(?v8, "^234", "i" )
#FILTER regex(?v8, "^234$", "i" )
#FILTER regex(?v8, "234$", "i" )
}   
}
LIMIT 5
