PREFIX rmpsIndex:<http://jazz.net/xmlns/rmps/index/1.0/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX jfs:<http://jazz.net/xmlns/foundation/1.0/>
PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX fn:<http://www.w3.org/2005/xpath-functions#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX rmpsQIndex:<http://jazz.net/xmlns/rmps/index/quicksearch/1.0/>
SELECT DISTINCT ?serverUri ?name ?type ?typeName ?modified ?contributor ?creator ?created ?contentProvider ?publisher ?diagramTypeName ?g
WHERE {
{ GRAPH ?g { ?serverUri rmpsQIndex:discoverable "true";rmpsQIndex:quickSearch ?quickSearch0}
FILTER ( ?g = <https://localhost:9443/jazz/storage/com.ibm.xtools.rmps.index/1> || ?g = <https://localhost:9443/jazz/storage/com.ibm.xtools.rmps.index/7>
)
}FILTER( fn:matches(?quickSearch0, "(\\s)?diagram", "i"))
{ ?serverUri foaf:page ?f. }
OPTIONAL {?serverUri foaf:name ?name}
OPTIONAL {?serverUri rmpsIndex:diagramTypeName ?diagramTypeName.}
{ ?serverUri rdf:type ?type. }
{ ?f rmpsIndex:externalMetaData ?md; dcterms:publisher ?publisher.
?md dcterms:created ?created; dcterms:creator ?creator;
dcterms:contributor ?contributor; dcterms:modified ?modified. }
{ ?contentProvider <http://jazz.net/xmlns/rmps/1.0/provides> ?publisher. }
OPTIONAL { ?type dcterms:title ?typeName. } }
LIMIT 501 
