#!/bin/bash

# Run in TDBROOT
TDBROOT="${TDBROOT:-$HOME/Projects/TDB}"
DB_DESC="$TDBROOT/tdb.ttl"

# "none" does consume all nodes.
RESULTS=count
# ARGS="--set tdb:indexType=bplustree"
# ARGS="--set tdb:fileMode=mapped"

for q in $TDBROOT/Perf/DBpedia-1/query?.rq
do
  N=$(basename "$q")
  echo "==== $N ===="
  tdbquery --time --results $RESULTS --desc "$DB_DESC" $ARGS --query "$q"
  done

exit

for q in $TDBROOT/Perf/DBpedia-1/query?a.rq
do
  N="$(basename $q)"
  echo "==== $N ===="
  tdbquery --time --results $RESULTS --desc "$DB_DESC" $ARGS --query "$q"
  done
