#!/usr/bin/ruby

10000.times do |i|
  print '.' 
  result1 = system './s-put',    'http://localhost:3030/ds', 'http://example.com/graph', 'D.nt'
  result2 = system './s-delete', 'http://localhost:3030/ds', 'http://example.com/graph'
  
  if (!result1 || !result2) then
    STDERR.puts '\nFailed'
    exit 1
  end
end
