#!/bin/bash

## echo "For TDB, use ant ivy-setup-lib"
## exit 1

MODULE="$@"
#DEFAULT="TDB SDB Joseki3"
DEFAULT="TDB"


for m in $MODULE
do
  if [ "$m" = "ARQ" ]
      then
      echo "Error: can't snapshot ARQ to itself" 1>&2
      exit 1
  fi
  done

# Where to move the jars to
if [ "$MODULE" != "" ]
then
    LIBDIRS="$MODULE"
else
    LIBDIRS="${LIBDIR:-$DEFAULT}"
fi

## Remove path and version numbers.
function jarName
{
    local JAR="$1"
    local VER="$2"
    perl -e '$_=$ARGV[0] ; s!(.*/)?([^/]*)-\d.\d.\d(-.*).jar!$2$3.jar! ; print "$_\n"' $JAR
}

function version
{
    local JAR="$1"
    perl -e '$_=$ARGV[0] ; s!(.*/)?[^/]*-(\d.\d.\d).*.jar!$2! ; print "$_\n"' $JAR
}


## Make jar and sources 
mvn clean package

## Get version.
X=$(echo target/arq-*-tests.jar)
[ -e "$X" ] || { echo "No such tests jar" 1>&2 ; exit 1 ; }
VER=$X
VER=${VER#*/arq-}
VER=${VER%-tests.jar}

echo "ARQ version: $VER"

for d in $LIBDIRS
do
  echo "Moving ARQ jars to project $d"
  cp -u target/arq-$VER.jar ../$d/lib/
  cp -u target/arq-$VER-tests.jar ../$d/lib/

  cp -u target/arq-$VER-sources.jar ../$d/
  cp -u target/arq-$VER-test-sources.jar ../$d/

  ## Fix up 
  chmod u+rw ../$d/lib/arq*jar
  chmod u+rw ../$d/arq*jar
  # And Jena
  cp -u lib/jena.jar ../$d/lib
  cp -u lib/jenatest.jar ../$d/lib
done
