#!/bin/bash

rm -f lib/arq.jar lib/arq-extra.jar
## if [ ! -e "lib/arq.jar" -o ! -e "lib/arq-extra.jar" ]
## then
##     ant jars
##     fi
ant jar

for d in SDB Joseki3
do
  echo "Moving ARQ jars to project $d"
  cp -u lib/arq.jar ../$d/lib
  cp -u lib/arq-extra.jar ../$d/lib
  # cp -u lib/arq-sse.jar ../$d/lib
  done

## Keep the JARs around for Eclipse libraries
## rm -f lib/arq.jar
## rm -f lib/arq-extra.jar
## rm -f lib/arq-sse.jar

rm -f arq-src.zip

for d in src src-dev src-test
do
  ( cd $d ; find . -name test -prune -o -name .svn -prune -o -print | \
    xargs -n 200 zip -q ../arq-src.zip
  )
  done

for d in SDB
do
  echo "Moving arq-src.zip to project $d"
  cp -u arq-src.zip ../$d
  done
rm -f arq-src.zip
