#!/bin/bash

fuseki-server --mem --port 3535 /dataset &
PID=$!
# Server start
sleep 1
URL=http://localhost:3535/dataset

s-put "$URL/data" default D.nt
s-get "$URL/data" default

s-query --service="$URL/query" 'SELECT * {?s ?p ?o}'

kill $!