PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# contains integer
ASK {
	BIND("[1]"^^cdt:List AS ?list)
	FILTER(cdt:contains(?list, 1))
	FILTER(!cdt:contains(?list, 2))
}
