PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>

# nested lists given as literals
ASK {
	BIND("[1,'[2]'^^<http://w3id.org/awslabs/neptune/SPARQL-CDTs/List>]"^^cdt:List AS ?list)
	BIND("[2]"^^cdt:List AS ?list2)

	FILTER(cdt:contains(?list, 1))
	FILTER(!cdt:contains(?list, 2))
	FILTER(cdt:contains(?list, ?list2))
}
