PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND("[1]" AS ?list)
	BIND(cdt:contains(?list, 1) AS ?result)
	FILTER(!BOUND(?result))
}
