PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with nested list with one integer
ASK {
	BIND("[[1]]"^^cdt:List AS ?list)
	BIND((cdt:get(?list, 1)) AS ?l0)
	BIND((cdt:get(?l0, 1)) AS ?l1)
	FILTER(?l1 = 1)
}
