PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with two strings
ASK {
	BIND("['a', 'b']"^^cdt:List AS ?list)
	FILTER(cdt:get(?list, 1) = 'a')
	FILTER(cdt:get(?list, 2) = 'b')
}
