PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( ( "[1,1,1]"^^cdt:List <= "[1,2]"^^cdt:List ) AS ?result )
	FILTER( BOUND(?result) )
	FILTER( ?result = true )
}
