PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( ( "[null]"^^cdt:List <= "[null]"^^cdt:List ) AS ?result )

	FILTER( BOUND(?result) )
	FILTER( ?result = true )
}
