PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	FILTER( "[<http://example.org/>]"^^cdt:List = "[ <http://example.org/> ]"^^cdt:List )
}
