PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with one string
ASK {
	BIND("['a']"^^cdt:List AS ?list)
	FILTER(cdt:reverse(?list) = "['a']"^^cdt:List)
}
