PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND("[1,2,3,4,5,6,7,8,9,10]" AS ?list)
	BIND(cdt:subseq(?list, 2, 3) AS ?result)
	FILTER(!BOUND(?result))
}
