PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with two mixed types
ASK {
	BIND("['a', 1]"^^cdt:List AS ?list)
	FILTER(cdt:tail(?list) = "[1]"^^cdt:List)
}
