PREFIX : <http://example/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?subject ?predicate ?object ?triple {
  VALUES (?subject ?predicate ?object) {
    (:a :b :c)
    (UNDEF :b :c)
    (:a UNDEF :c)
    (:a :b UNDEF)
  }
  BIND(TRIPLE(?subject, ?predicate, ?object) AS ?triple)
}
