#!/usr/bin/env bash

M2="/home/afs/.m2/repo"
export FUSEKI_HOME="${HOME}/Jena/jena-fuseki2/jena-fuseki-core"
export FUSEKI_BASE="${HOME}/tmp/run"



## "(cd jena-fuseki-core ; mvn dependency:build-classpath -DincludeScope=runtime""

export JENA_DEP="$(cat fuseki-classpath)"
CP="$JENA_DEP"

JENA="$HOME/Jena"
# Local development binaries.
DIRS1="$JENA/jena-tdb $JENA/jena-arq $JENA/jena-core $JENA/jena-base $JENA/jena-text $JENA/jena-fuseki2/jena-fuseki-core" 

MANTIS="${HOME}/Mantis"
DIRS2="$(echo $MANTIS/dboe-{base,index,index-btree,quack,transaction,trans-data})"

for D in $DIRS1 $DIRS2  $MANTIS/tdb2
do
    CP="$CP:$D/target/classes"
done

## echo $CP
## exit
#JVM_ARGS="${JVM_ARGS:--Xmx4G}
set -- "--conf" "config.ttl"

exec java -cp "$CP" $JVM_ARGS $FUSEKI_LOG org.apache.jena.fuseki.cmd.FusekiCmd "$@"
