#!/bin/bash

M2="$HOME/.m2/repo"

CPX="
${M2}/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar
${M2}/com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.jar
${M2}/com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.jar
${M2}/com/github/jsonld-java/jsonld-java/0.5.1/jsonld-java-0.5.1.jar
${M2}/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
${M2}/junit/junit/4.12-beta-3/junit-4.12-beta-3.jar
${M2}/log4j/log4j/1.2.17/log4j-1.2.17.jar
${M2}/org/apache/commons/commons-csv/1.0/commons-csv-1.0.jar
${M2}/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
${M2}/org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.jar
${M2}/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar
${M2}/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar
${M2}/org/apache/jena/jena-arq/2.13.0-SNAPSHOT/jena-arq-2.13.0-SNAPSHOT.jar
${M2}/org/apache/jena/jena-core/2.13.0-SNAPSHOT/jena-core-2.13.0-SNAPSHOT.jar
${M2}/org/apache/jena/jena-iri/1.1.2-SNAPSHOT/jena-iri-1.1.2-SNAPSHOT.jar
${M2}/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar
${M2}/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
${M2}/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar
${M2}/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar
${M2}/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar
${M2}/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar
${M2}/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
"

CP=""
for x in $CPX
do
    if [[ $CP == "" ]]
    then
	CP="$x"
    else
	CP="$CP:$x"
    fi
done

MANTIS="$HOME/Mantis"
for x in dboe-base dboe-index dboe-index-test dboe-transaction
do
    CP="$MANTIS/$x/target/classes:$CP"
    CP="$MANTIS/$x/target/test-classes:$CP"
done    

ARGS="" 
#ARGS="-Xmx1G" 
ARGS="$ARGS -Dbpt:checking=true"
ARGS="$ARGS -Dbpt:duplication=true"


CP="target/classes:target/test-classes:$CP"
#echo $CP
#java -cp "$CP" org.seaborne.dboe.trans.bplustree.rewriter.CmdTestBPlusTreeRewriter "$@"
java $ARGS -cp "$CP" org.seaborne.dboe.trans.bplustree.soak.CmdTestBPlusTree "$@"
