/******************************************************************
 * File:        StandardValidityReport.java
 * Created by:  Dave Reynolds
 * Created on:  09-Feb-03
 * 
 * (c) Copyright 2003, Hewlett-Packard Company, all rights reserved.
 * [See end of file]
 * $Id: StandardValidityReport.java,v 1.1 2003-02-10 10:13:24 der Exp $
 *****************************************************************/
package com.hp.hpl.jena.reasoner;

import java.util.*;

/**
 *
 * @author <a href="mailto:der@hplb.hpl.hp.com">Dave Reynolds</a>
 * @version $Revision: 1.1 $ on $Date: 2003-02-10 10:13:24 $
 */
public class StandardValidityReport implements ValidityReport {

    /** The total set of error reports */
    protected List reports = new ArrayList();
    
    /** Flag to indicate if there are any error reports so far */
    protected boolean isError;
    
    /**
     * Add a new error report
     * @param error true if the report is an error, false if it is just a warning
     * @param type a string giving a reasoner-dependent classification for the report
     * @param description a textual description of the problem
     */
    public void add(boolean error, String type, String description) {
        reports.add(new Report(error, type, description));
        if (error) isError = true;
    }
    
    /**
     * Add a new error report
     * @param report a ValidityReport.Report to add, can be null 
     */
    public void add(ValidityReport.Report report) {
        if (report == null) return;
        reports.add(report);
        if (report.isError) isError = true;
    }
    
    /**
     * Return true if there are no problems reported by the validation
     */
    public boolean isValid() {
        return !isError;
    }
    
    /**
     * Return a count of the number of warning or error reports
     * generated by the validation.
     */
    public int size() {
        return reports.size();
    }
    
    /**
     * Return the i'th error/warning report in the set
     */
    public Report get(int i) {
        return (Report)reports.get(i);
    }

}
