PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	{
		SELECT * WHERE {
			VALUES (?id ?map) {
				(1  "{ 1: '01'^^<http://www.w3.org/2001/XMLSchema#integer> }"^^cdt:Map)
				(2  "{ 1: '001'^^<http://www.w3.org/2001/XMLSchema#integer> }"^^cdt:Map)
			}
		}
		ORDER BY ?map LIMIT 1
	}
	FILTER ( (?id = 1) || (?id = 2) )
}
