PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	{
		SELECT * WHERE {
			VALUES (?id ?list) {
				(1  "[<http://example.org>, <http://example.org/1>]"^^cdt:List)
				(2  "[<http://example.org>, <http://example.org/2>]"^^cdt:List)
			}
		}
		ORDER BY ?list LIMIT 1
	}
	FILTER (?id = 1)
}
