PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	{
		SELECT * WHERE {
			VALUES (?id ?list) {
				(1  "[1]"^^cdt:List)
				(2  "[ 2]"^^cdt:List)  # the space is on purpose, to make sure the comparison is not done in terms of the lexical forms
			}
		}
		ORDER BY ?list LIMIT 1
	}
	FILTER (?id = 1)
}
