PREFIX :           <http://example.org/>
PREFIX apf:        <java:com.hp.hpl.jena.query.pfunction.library.>
PREFIX xsd:        <http://www.w3.org/2001/XMLSchema#>

SELECT ?ns
{
  xsd:integer apf:splitIRI (?ns [])
}
