# ==== Ex 3 : Proteins with publications by authors with matching names
# 
# SELECT 
#   ?protein, ?author, ?title
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :modified ?modified] AND 
#   [?protein :citation ?citation] AND 
#   [?citation :author ?author] AND 
#   ?author ~ "bairoch %" AND 
#   [?citation :title ?title] 
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf

PREFIX :     <urn:lsid:uniprot.org:ontology:>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT 
  ?protein ?author ?title 
{
  ?citation :author ?author .
  FILTER ( regex(?author, "^Bairoch ", "i") ) .
  ?citation :title ?title .
  ?protein :citation ?citation .
#  ?protein :modified ?modified .
  ?protein rdf:type :Protein .
}
