# ==== Ex 7 : Sequences of bacterial proteins
# 
# SELECT 
#   ?protein, ?aa
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :organism taxon:2] AND 
#   [?protein :sequence ?s] AND 
#   [?s rdf:value ?aa]
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf, 
#   "http://www.w3.org/2000/01/rdf-schema#" AS rdfs,
#   "urn:lsid:uniprot.org:taxonomy:" AS taxon

PREFIX :      <urn:lsid:uniprot.org:ontology:>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX taxon: <urn:lsid:uniprot.org:taxonomy:>

SELECT  ?protein ?aa
{
  ?protein rdf:type :Protein .
  ?protein :organism <urn:lsid:uniprot.org:taxonomy:2> .
  ?protein :sequence ?s .
  ?s rdf:value ?aa
}
