PREFIX :      <urn:lsid:uniprot.org:ontology:>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX taxon: <urn:lsid:uniprot.org:taxonomy:>

SELECT  ?protein ?aa
{
  ?protein :organism <urn:lsid:uniprot.org:taxonomy:2> .
  ?protein rdf:type :Protein .
  ?protein :sequence ?s .
  ?s rdf:value ?aa
}
