PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX :       <http://example/>
PREFIX pf:     <http://jena.hpl.hp.com/ARQ/property#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

SELECT *
{
    ?lit pf:textMatch ('+document' 0.7 1)
}
