PREFIX  jfn:  <java:com.hp.hpl.jena.query.function.library.>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX     :  <http://example.org/> 

SELECT ?x ?list
{ { ?x :p ?list } UNION { ?x :q ?list }
  FILTER jfn:listMember(?list, rdf:nil)
}
