PREFIX  jfn:  <java:com.hp.hpl.jena.query.function.library.>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX     :  <http://example.org/> 

SELECT ?x ?list
{ ?x :p ?list
  FILTER jfn:listMember(3, 3)
}
