PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?x ?m
{ 
    # Reversing gets the same results (different efficiency)
    ?x rdfs:member ?m . 
    ?x rdfs:member 1 .
}
