# Query3
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Publication .
	?x ub:publicationAuthor <http://www.Department0.University0.edu/AssistantProfessor0> .
}
# (type Publication ?X)
# (publicationAuthor ?X http://www.Department0.University0.edu/AssistantProfessor0)
# - This query is similar to Query 1 but class Publication has a wide hierarchy.

