# Query7
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Student .
	?y rdf:type ub:Course .
	<http://www.Department0.University0.edu/AssociateProfessor0> ub:teacherOf ?y .
	?x ub:takesCourse ?y .
}
# (type Student ?X)
# (type Course ?Y)
# (teacherOf http://www.Department0.University0.edu/AssociateProfessor0 ?Y)
# (takesCourse ?X ?Y)
# - This query is similar to Query 6 in terms of class Student but it increases in the number of classes and properties and its selectivity is high.

