# Query2
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:GraduateStudent .
	?y rdf:type ub:University .
	?z rdf:type ub:Department .
	?x ub:memberOf ?z .
	?z ub:subOrganizationOf ?y .
	?x ub:undergraduateDegreeFrom ?y .
}
# (type GraduateStudent ?X)
# (type University ?Y)
# (type Department ?Z)
# (memberOf ?X ?Z)
# (subOrganizationOf ?Z ?Y)
# (undergraduateDegreeFrom ?X ?Y)
# - This query increases in complexity: 3 classes and 3 properties are involved. Additionally, there is a triangular pattern of relationships between the objects involved.

