# Query10
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/%7Ezhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Student .
	?x ub:takesCourse <http://www.Department0.University0.edu/GraduateCourse0> .
}
# (type Student ?X)
# (takesCourse ?X http://www.Department0.University0.edu/GraduateCourse0)
# - This query differs from Query 6, 7, 8 and 9 in that it only requires the (implicit) subClassOf relationship between GraduateStudent and Student, i.e., subClassOf relationship between UndergraduateStudent and Student does not add to the results.

