# Query5
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/%7Ezhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Person .
	?x ub:memberOf <http://www.Department0.University0.edu> .
}
# (type Person ?X)
# (memberOf ?X http://www.Department0.University0.edu)
# - This query assumes subClassOf relationship between Person and its subclasses and subPropertyOf relationship between memberOf and its subproperties. Moreover, class Person features a deep and wide hierarchy.

