# Query8
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/%7Ezhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Student .
	?y rdf:type ub:Department .
	?x ub:memberOf ?y .
	?y ub:subOrganizationOf <http://www.University0.edu> .
	?x ub:emailAddress ?z .
}
# (type Student ?X)
# (type Department ?Y)
# (memberOf ?X ?Y)
# (subOrganizationOf ?Y http://www.University0.edu)
# (emailAddress ?X ?Z)
# - This query is further more complex than Query 7 by including one more property.

