# Query9
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Student .
	?y rdf:type ub:Faculty .
	?z rdf:type ub:Course .
	?x ub:advisor ?y .
        ?x ub:takesCourse ?z .
        ?y ub:teacherOf ?z .
}
#(type Student ?X)
#(type Faculty ?Y)
#(type Course ?Z)
#(advisor ?X ?Y)
#(takesCourse ?X ?Z)
#(teacherOf ?Y ?Z)
#- Besides the aforementioned features of class Student and the wide hierarchy of class Faculty, like Query 2, this query is characterized by the most classes and properties in the query set and there is a triangular pattern of relationships.

