# Query12
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Chair .
	?y rdf:type ub:Department .
	?x ub:worksFor ?y .
	?y ub:subOrganizationOf <http://www.University0.edu> .
}
# (type Chair ?X)
# (type Department ?Y)
# (worksFor ?X ?Y)
# (subOrganizationOf ?Y http://www.University0.edu)
# - The benchmark data do not produce any instances of class Chair. Instead, each Department individual is linked to the chair professor of that department by property headOf. Hence this query requires realization, i.e., inference that that professor is an instance of class Chair because he or she is the head of a department. Input of this query is small as well.

