#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# How to do a file upload in curl

# GSP strict
U='http://localhost:3030/ds/data?graph=http://example/G'
# PUT
## curl --upload-file D.ttl --header 'Content-Type: text/turtle' "$U"

# POST
curl -XPOST --upload-file D.ttl --header 'Content-Type: text/turtle' "$U"

# GSP strict / file upload
## curl -F 'file=@D.ttl' http://localhost:3030/ds/data

# Quads to GSP

## curl -F 'file=@D.ttl' http://localhost:3030/ds/data
## curl -F 'file=@D.trig' http://localhost:3030/ds/data

# Quads to graph : NGs in data ignored
# curl -F 'file=@D.trig' 'http://localhost:3030/ds/data?default'
#curl -F 'file=@D.trig' 'http://localhost:3030/ds/data?graph=http://example/G'

# Dataset
## curl -F 'file=@D.trig' http://localhost:3030/ds

# Upload service
## curl -F 'file=@D.trig' -F 'name=http://graph/' 'http://localhost:3030/ds/upload'


echo "==== Dataset"
curl  http://localhost:3030/ds
