#!/bin/bash

cat <<EOF
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .
@prefix mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#> .
@prefix qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#> .

<>  rdf:type mf:Manifest ;
    rdfs:comment "DAWG test cases" ;
    mf:entries
    (
EOF

i=1
while [ -e "ex$i.rq" ]
do
  echo "     [  mf:name    \"Example $i\" ;"
  echo "        mf:action"
  echo "        [ qt:query  <ex$i.rq> ; qt:data   <ex$i.ttl> ] ;"
  echo "        mf:result  <ex$i-r.ttl>"
  echo "     ]"
  i=$((i+1))
done


cat <<EOF
   ).
EOF