PREFIX dc10:  <http://purl.org/dc/elements/1.0/>
PREFIX dc11:  <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?title
WHERE  { { ?book dc10:title  ?title } UNION { ?book dc11:title  ?title } }
