#!/bin/bash

D=$(find ARQ Optimizer Update LARQ ! -name . ! -name .. ! \( -name .svn -prune \) -type d)

MISSING=0
for d in $D
  do
  JDIR=~/Projects/Jena2/testing/$d
  if [ ! -e $JDIR ]
      then
      echo "Missing: $JDIR"
      MISSING=1
  fi
done

if [ $MISSING != 0 ]
then
    exit 1 ;
fi

#exit 0 ;

for d in $D
  do
  JDIR=~/Projects/Jena2/testing/$d
  if [ ! -e $JDIR ]
      then
      echo "**** Missing: $JDIR"
  else
      rm -f $JDIR/*.*
      cp ~/Projects/ARQ/testing/$d/*.* $JDIR
  fi
done

cp ARQ/manifest-*.ttl ~/Projects/Jena2/testing/ARQ/

#echo "** Check ../LARQ"
#echo "** Check ../Update"
