PREFIX sdb:      <http://jena.hpl.hp.com/2007/sdb#>
PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:	 <http://www.w3.org/2000/01/rdf-schema#>
PREFIX desc:     <./StoreDesc/>
PREFIX list:     <http://jena.hpl.hp.com/ARQ/list#>

SELECT ?desc ?label
{ [] rdf:type sdb:StoreList ;
     sdb:list ?l .
  ?l list:member [ rdfs:label ?label ; sdb:description ?desc ]
}