#!/bin/bash

B="https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource"

for n in 1 2 3 4 5 6 7 8 9
do
  echo "==== Load $n"
  tdbloader --loc DB resource$n.nt
  tdbloader --loc DB --graph "$B$n" resource$n.nt
  done
