PREFIX  jfs:  <http://jazz.net/xmlns/foundation/1.0/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  rmpsIndex: <http://jazz.net/xmlns/rmps/index/1.0/>
PREFIX  rmpsQIndex: <http://jazz.net/xmlns/rmps/index/quicksearch/1.0/>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  fn:   <http://www.w3.org/2005/xpath-functions#>
PREFIX  dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT  ?serverUri ?name ?type ?typeName ?modified ?contributor ?creator ?created ?contentProvider ?publisher ?diagramTypeName
WHERE
  { { GRAPH ?g
        { ?serverUri  rmpsQIndex:discoverable  true ;
                    rmpsQIndex:quickSearch  ?quickSearch0 ;
                    rmpsQIndex:quickSearch  ?quickSearch1 ;
                    rmpsQIndex:quickSearch  ?quickSearch2 .
        }
      FILTER ( ( ( ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource1> ) || ( ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource2> ) ) || ( ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource3> ) )
    }
    { FILTER ( ( fn:matches(?quickSearch0, "(\\s)?class", "i") && fn:matches(?quickSearch1, "(\\s)?diagram", "i") ) && fn:matches(?quickSearch2, "(\\s)?main", "i") ) }
##     { ?serverUri  foaf:page  ?f . }
##     OPTIONAL
##       { ?serverUri  foaf:name  ?name . }
##     OPTIONAL
##       { ?serverUri  rmpsIndex:diagramTypeName  ?diagramTypeName . }
##     { ?serverUri  rdf:type  ?type . }
##     { ?f   rmpsIndex:externalMetaData  ?md ;
##            dcterms:publisher     ?publisher .
##       ?md  dcterms:created       ?created ;
##            dcterms:creator       ?creator ;
##            dcterms:contributor   ?contributor ;
##            dcterms:modified      ?modified .
##     }
## ##     { ?contentProvider
##                 <http://jazz.net/xmlns/rmps/1.0/provides>  ?publisher .
##     }
    OPTIONAL
      { ?type  dcterms:title  ?typeName . }
  }
LIMIT   201

## PREFIX rmpsIndex:<http://jazz.net/xmlns/rmps/index/1.0/>
## PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
## PREFIX jfs:<http://jazz.net/xmlns/foundation/1.0/>
## PREFIX dcterms:<http://purl.org/dc/terms/>
## PREFIX fn:<http://www.w3.org/2005/xpath-functions#>
## PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
## PREFIX foaf:<http://xmlns.com/foaf/0.1/>
## PREFIX rmpsQIndex:<http://jazz.net/xmlns/rmps/index/quicksearch/1.0/>
## SELECT DISTINCT ?serverUri ?name ?type ?typeName ?modified ?contributor ?creator ?created ?contentProvider ?publisher ?diagramTypeName
## WHERE {
## { GRAPH ?g { ?serverUri rmpsQIndex:discoverable "true"^^xsd:boolean ;rmpsQIndex:quickSearch ?quickSearch0;rmpsQIndex:quickSearch ?quickSearch1;rmpsQIndex:quickSearch ?quickSearch2}.
## FILTER ( ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource1>
## || ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource2>
## || ?g = <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource3>
## )
## } { FILTER( fn:matches(?quickSearch0, "(\\s)?class", "i")
## && fn:matches(?quickSearch1, "(\\s)?diagram", "i")
## && fn:matches(?quickSearch2, "(\\s)?main", "i")) }
## { ?serverUri foaf:page ?f. }
## OPTIONAL {?serverUri foaf:name ?name}
## OPTIONAL {?serverUri rmpsIndex:diagramTypeName ?diagramTypeName.}
## { ?serverUri rdf:type ?type. }
## { ?f rmpsIndex:externalMetaData ?md; dcterms:publisher ?publisher.
## ?md dcterms:created ?created; dcterms:creator ?creator;
## dcterms:contributor ?contributor; dcterms:modified ?modified. }
## { ?contentProvider <http://jazz.net/xmlns/rmps/1.0/provides> ?publisher. }
## OPTIONAL { ?type dcterms:title ?typeName. } }
## LIMIT 201
