PREFIX  jfs:  <http://jazz.net/xmlns/foundation/1.0/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  rmpsIndex: <http://jazz.net/xmlns/rmps/index/1.0/>
PREFIX  rmpsQIndex: <http://jazz.net/xmlns/rmps/index/quicksearch/1.0/>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  fn:   <http://www.w3.org/2005/xpath-functions#>
PREFIX  dcterms: <http://purl.org/dc/terms/>

## SELECT DISTINCT  ?serverUri ?name ?type ?typeName ?modified ?contributor ?creator ?created ?contentProvider ?publisher ?diagramTypeName
SELECT *
WHERE
  { { GRAPH <https://shelsen.torolab.ibm.com:9443/jazz/storage/com.ibm.xtools.rmps.index/resource1>
        { ?serverUri  rmpsQIndex:discoverable  true ;
                    rmpsQIndex:quickSearch  ?quickSearch0 ;
                    rmpsQIndex:quickSearch  ?quickSearch1 ;
                    rmpsQIndex:quickSearch  ?quickSearch2 .
        }
    }
    { FILTER ( ( fn:matches(?quickSearch0, "(\\s)?class", "i") && fn:matches(?quickSearch1, "(\\s)?diagram", "i") ) && fn:matches(?quickSearch2, "(\\s)?main", "i") ) }
  }
