/* Generated By:JavaCC: Do not edit this line. ARQParserConstants.java */
/*
 * (c) Copyright 2004, 2005, 2006, 2007 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package com.hp.hpl.jena.sparql.lang.arq ;

public interface ARQParserConstants {

  int EOF = 0;
  int WS = 8;
  int SINGLE_LINE_COMMENT = 9;
  int IRIref = 10;
  int PNAME_NS = 11;
  int PNAME_LN = 12;
  int BLANK_NODE_LABEL = 13;
  int VAR1 = 14;
  int VAR2 = 15;
  int LANGTAG = 16;
  int A2Z = 17;
  int A2ZN = 18;
  int KW_A = 19;
  int BASE = 20;
  int PREFIX = 21;
  int SELECT = 22;
  int DISTINCT = 23;
  int REDUCED = 24;
  int DESCRIBE = 25;
  int CONSTRUCT = 26;
  int ASK = 27;
  int LIMIT = 28;
  int OFFSET = 29;
  int ORDER = 30;
  int BY = 31;
  int ASC = 32;
  int DESC = 33;
  int NAMED = 34;
  int FROM = 35;
  int WHERE = 36;
  int AND = 37;
  int GRAPH = 38;
  int OPTIONAL = 39;
  int UNION = 40;
  int SERVICE = 41;
  int AS = 42;
  int EXT = 43;
  int GROUP = 44;
  int HAVING = 45;
  int AGG = 46;
  int COUNT = 47;
  int MIN = 48;
  int MAX = 49;
  int SUM = 50;
  int AVG = 51;
  int STDDEV = 52;
  int FILTER = 53;
  int BOUND = 54;
  int STR = 55;
  int DTYPE = 56;
  int LANG = 57;
  int LANGMATCHES = 58;
  int IS_URI = 59;
  int IS_IRI = 60;
  int IS_BLANK = 61;
  int IS_LITERAL = 62;
  int REGEX = 63;
  int SAME_TERM = 64;
  int TRUE = 65;
  int FALSE = 66;
  int DIGITS = 67;
  int INTEGER = 68;
  int DECIMAL = 69;
  int DOUBLE = 70;
  int INTEGER_POSITIVE = 71;
  int DECIMAL_POSITIVE = 72;
  int DOUBLE_POSITIVE = 73;
  int INTEGER_NEGATIVE = 74;
  int DECIMAL_NEGATIVE = 75;
  int DOUBLE_NEGATIVE = 76;
  int EXPONENT = 77;
  int QUOTE_3D = 78;
  int QUOTE_3S = 79;
  int ECHAR = 80;
  int STRING_LITERAL1 = 81;
  int STRING_LITERAL2 = 82;
  int STRING_LITERAL_LONG1 = 83;
  int STRING_LITERAL_LONG2 = 84;
  int LPAREN = 85;
  int RPAREN = 86;
  int NIL = 87;
  int LBRACE = 88;
  int RBRACE = 89;
  int LBRACKET = 90;
  int RBRACKET = 91;
  int ANON = 92;
  int SEMICOLON = 93;
  int COMMA = 94;
  int DOT = 95;
  int EQ = 96;
  int NE = 97;
  int GT = 98;
  int LT = 99;
  int LE = 100;
  int GE = 101;
  int BANG = 102;
  int TILDE = 103;
  int COLON = 104;
  int SC_OR = 105;
  int SC_AND = 106;
  int PLUS = 107;
  int MINUS = 108;
  int STAR = 109;
  int SLASH = 110;
  int DATATYPE = 111;
  int AT = 112;
  int PN_CHARS_BASE = 113;
  int PN_CHARS_U = 114;
  int PN_CHARS = 115;
  int PN_PREFIX = 116;
  int PN_LOCAL = 117;
  int VARNAME = 118;
  int UNKNOWN = 119;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"<<\"",
    "\">>\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"service\"",
    "\"as\"",
    "\"ext\"",
    "\"group\"",
    "\"having\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"stdev\"",
    "\"filter\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
