#!/bin/bash

function syntaxCheck
{
    FILE="$1"
    echo "Syntax check: $FILE"
    n3 -n -rdf "$FILE"
}

function proc
{
    TMP=TT
    FILE="$1"
    CLASS="$2"
    NS="$3"
    echo "Schemagen: $FILE"
    schemagen --rdfs -i "$FILE" -n "$CLASS" -a "$NS" -o "$CLASS".java -e N3
    # Add imports
    echo "package com.hp.hpl.jena.sdb.core ;" >> "$TMP"
    echo >>"$TMP"
    cat "$CLASS".java >> "$TMP"
    mv "$TMP" "$CLASS".java
}

syntaxCheck schema-config.ttl
proc schema-config.ttl SchemaConfigVocab \
     "http://jena.hpl.hp.com/2005/12/schema#"
#mv SchemaConfigVocab.java ../src/com/hp/hpl/jena/sdb/core 
