package com.hp.hpl.jena.sparql.vocabulary ;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from EARL.ttl 
 * @author Auto-generated by schemagen on 09 Jul 2007 17:33 
 */
public class VocabEARL {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/earl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property assertedBy = m_model.createProperty( "http://www.w3.org/ns/earl#assertedBy" );
    
    public static final Property info = m_model.createProperty( "http://www.w3.org/ns/earl#info" );
    
    public static final Property outcome = m_model.createProperty( "http://www.w3.org/ns/earl#outcome" );
    
    public static final Property mode = m_model.createProperty( "http://www.w3.org/ns/earl#mode" );
    
    /** <p>Assertor assisting to determine assertion result</p> */
    public static final Property helpAssertor = m_model.createProperty( "http://www.w3.org/ns/earl#helpAssertor" );
    
    public static final Property result = m_model.createProperty( "http://www.w3.org/ns/earl#result" );
    
    /** <p>Assertor mainly responsible for determining assertion result</p> */
    public static final Property mainAssertor = m_model.createProperty( "http://www.w3.org/ns/earl#mainAssertor" );
    
    public static final Property pointer = m_model.createProperty( "http://www.w3.org/ns/earl#pointer" );
    
    public static final Property sourceCopy = m_model.createProperty( "http://www.w3.org/ns/earl#sourceCopy" );
    
    public static final Property test = m_model.createProperty( "http://www.w3.org/ns/earl#test" );
    
    public static final Property subject = m_model.createProperty( "http://www.w3.org/ns/earl#subject" );
    
    public static final Property context = m_model.createProperty( "http://www.w3.org/ns/earl#context" );
    
}
