PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  test: <http://www.myOntDomain.com/test#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?Date
WHERE
  { ?Event  rdf:type      test:Event ;
            test:hasDate  ?Date .
    FILTER ( ?Date = "2010-01-19T16:00:00Z"^^xsd:dateTime )
  }
