# Positive test: product of type promotion within the xsd:decimal type tree.
# $Id: boolean-logical-OR.rq,v 1.7 2007-05-21 11:13:10 andy_seaborne Exp $

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?one
 WHERE { ?one rdf:value ?oneL .
         FILTER ( (TRUE || FALSE) = ?oneL ) }
