#!/bin/bash
# Export the web site to jena.sourceforge.net
# Assumes you have ssh set up correctly.

echo "Best to do a build and copy the doc/ directory from the distribution"

HOST="shell.sourceforge.net"
LOC="/home/groups/j/je/jena/htdocs"

PAGES=$(cat <<EOF
documentation.html
downloads.html
index.html
license.html
resources.html
support.html

migrate1-2.html
reify-api.html
reify-spi.html
jena2-api-changes.html
enh-node-howto.html
EOF
)

DIRS=$(cat <<EOF
DB/
FAQ/
IO/
RDQL/
examples/
how-to/
inference/
ontology/
tutorial/
images/
styles/
javadoc/
EOF
)

STYLE=$(cat <<EOF
styles/site.css
styles/usermanual.css
styles/tutorial.css
EOF
)

#images/JenaLogo.png
IMAGES=$(cat <<EOF
images/JenaLogoSimple.png
images/rdf_w3c_icon.gif
images/sflogo-type1.png
EOF
)

# Need to fix up line endings?

# Copy to a release ara, them copy all to SourceForge

COPY="pscp -load afs@jena.hpl.hp.com"

$COPY -r $PAGES   ~/WWW/Jena/WebSite
$COPY -r $STYLE   ~/WWW/Jena/WebSite/styles
$COPY -r $IMAGES  ~/WWW/Jena/WebSite/images

