PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  schema: <http://www.cogsci.princeton.edu/~wn/schema/>

SELECT  ?distinct ?word ?superTypeA ?superTypeB ?superTypeC ?superTypeD
WHERE
  { ?concept  rdf:type          schema:Verb ;
              schema:hyponymOf  ?h1 ;
              schema:wordForm   ?word .
    ?h1       schema:hyponymOf  ?h2 ;
              schema:wordForm   ?superTypeA .
    ?h2       schema:hyponymOf  ?h3 ;
              schema:wordForm   ?superTypeB .
    ?h3       schema:hyponymOf  ?h4 ;
              schema:wordForm   ?superTypeC .
    ?h4       schema:wordForm   ?superTypeD .
  }
