PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX ex:     <http://example.org/>

ASK {
	BIND( "{ '1': _:b1, '2': 42, '3': {'4': _:b2} }"^^cdt:Map AS ?map )

	BIND( cdt:get(?map,'1') AS ?e1 )
	BIND( cdt:get(?map,'3') AS ?innermap )
	BIND( cdt:get(?innermap,'4') AS ?e3 )

	FILTER( isBLANK(?e1) )
	FILTER( isBLANK(?e3) )
	FILTER( ?e1 != ?e3 )
}
