PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX ex:     <http://example.org/>

ASK {
	ex:s ex:p1 ?map .
	ex:s ex:p2 ?bn .

	BIND( cdt:get(?map,'1') AS ?e1 )

	FILTER( isBLANK(?e1) )
	FILTER( isBLANK(?bn) )
	FILTER( ?e1 != ?bn )
}
