PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX ex:     <http://example.org/>

ASK {
	BIND( "[_:b, 42]"^^cdt:List AS ?list )
	ex:s ex:p ?bn .

	BIND( cdt:get(?list,1) AS ?e1 )

	FILTER( isBLANK(?e1) )
	FILTER( isBLANK(?bn) )
	FILTER( ?e1 != ?bn )
}
