PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
    <<?s ?p ?o ~ :iri >> ex:author ex:Bob .
    << ex:Moscow a ex:City ~ :iri >> ex:author ?person .
    # TODO: See if this should be throwing an error
    << _:b ex:x () ~ :iri >> ex:broken true .
}
