#!/bin/bash

function parse
{
    local FN=$1
    echo "==== $FN"
    uparse --strict --file "$FN"  > /dev/null
}

function action
{
    local FN=$1
    echo "==== $FN"
    cat "$FN"
    echo "- - - - - - - - - - - - - - - - - - - - -"
    update --strict --dump --file "$FN" | rdfcat --out TTL -t -
}


U="add-first.ru add-last.ru del-first.ru del-last.ru delete-list-1.ru delete-list-2.ru"

for u in $U
do
    parse $u
    done

for u in $U
do
    action $u
    done
