# Query1
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:GraduateStudent .
	?x ub:takesCourse <http://www.Department0.University0.edu/GraduateCourse0> .
}
# (type GraduateStudent ?X)
# (takesCourse ?X http://www.Department0.University0.edu/GraduateCourse0)
# - This query bears large input and high selectivity. It queries about just one class and one property and does not assume any hierarchy information or inference.

