# Query4
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT * WHERE
{
	?x rdf:type ub:Professor .
	?x ub:worksFor <http://www.Department0.University0.edu> .
	?x ub:name ?y1 .
	?x ub:emailAddress ?y2 .
	?x ub:telephone ?y3 .
}
# (type Professor ?X)
# (worksFor ?X http://www.Department0.University0.edu)
# (name ?X ?Y1)
# (emailAddress ?X ?Y2)
# (telephone ?X ?Y3)
# - This query has small input and high selectivity. It assumes subClassOf relationship between Professor and its subclasses. Class Professor has a wide hierarchy. Another feature is that it queries about multiple properties of a single class.

