PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>

ASK {
	{
		SELECT (FOLD(DISTINCT ?v ORDER BY ASC(?sort)) AS ?list)
		WHERE {
			VALUES (?sort ?v) {
				(1 1)
				(3 3)
				(2 2)
				(2 2)
				(3 4)
			}
		}
	}

	FILTER( cdt:size(?list) = 4 )

	BIND( cdt:get(?list, 1) AS ?e1 )
	BIND( cdt:get(?list, 2) AS ?e2 )
	BIND( cdt:get(?list, 3) AS ?e3 )
	BIND( cdt:get(?list, 4) AS ?e4 )

	FILTER( ?e1 = 1 )
	FILTER( ?e2 = 2 )
	FILTER(
		( (?e3=3) && (?e4=4) )
		||
		( (?e3=4) && (?e4=3) )
	)
}
