#!/usr/bin/perl
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Write a run script.

$POM="pom.xml" ;
$POM = @ARGV[0] if ( defined(@ARGV[0]) ) ;

if ( ! -e "$POM" )
{
    print STDERR "No POM file: $POM\n" ;
    exit 1 ;
}
$M2=$ENV{'M2_REPO'} ;
print "#!/bin/bash\n" ;
print "# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0" ;
print "\n" ;
print 'XCP="' ;

open(X, "mvn -f $POM dependency:build-classpath |") ;
while(<X>)
{
    next if /\[INFO\]/ ;
    next if /^Download/ ;
    chop ;
    #s!$M2/org/apache/jena/jena-[^/]*/[^/]*/[^/]*.jar:!!g ;
    print "$_" ;
}
print "\"\n" ;
print "\n" ;

print "if [ \"\$CP\" != \'\' ]\n" ;
print "then\n" ;
print "   XCP=\"\$CP:\$XCP\"\n" ;
print "fi\n" ;
print "\n" ;
print "echo \"\$XCP\"\n" ;

