/* Generated By:JavaCC: Do not edit this line. TurtleParserConstants.java */
/*
 * (c) Copyright 2006 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package com.hp.hpl.jena.n3.turtle.parser ;

public interface TurtleParserConstants {

  int EOF = 0;
  int PLING = 1;
  int VBAR = 2;
  int CARROT = 3;
  int FPATH = 4;
  int RPATH = 5;
  int WS = 11;
  int SINGLE_LINE_COMMENT = 12;
  int KW_A = 13;
  int PREFIX = 14;
  int BASE = 15;
  int TRUE = 16;
  int FALSE = 17;
  int INTEGER = 18;
  int DECIMAL = 19;
  int DOUBLE = 20;
  int EXPONENT = 21;
  int QUOTE_3D = 22;
  int QUOTE_3S = 23;
  int ECHAR = 24;
  int STRING_LITERAL1 = 25;
  int STRING_LITERAL2 = 26;
  int STRING_LITERAL_LONG1 = 27;
  int STRING_LITERAL_LONG2 = 28;
  int DIGITS = 29;
  int HEX = 30;
  int IRIref = 31;
  int PNAME_NS = 32;
  int PNAME_LN = 33;
  int BLANK_NODE_LABEL = 34;
  int VAR = 35;
  int LANGTAG = 36;
  int A2Z = 37;
  int A2ZN = 38;
  int LPAREN = 39;
  int RPAREN = 40;
  int NIL = 41;
  int LBRACE = 42;
  int RBRACE = 43;
  int LBRACKET = 44;
  int RBRACKET = 45;
  int ANON = 46;
  int SEMICOLON = 47;
  int COMMA = 48;
  int DOT = 49;
  int EQ = 50;
  int ARROW = 51;
  int DOLLAR = 52;
  int QMARK = 53;
  int TILDE = 54;
  int COLON = 55;
  int STAR = 56;
  int SLASH = 57;
  int RSLASH = 58;
  int DATATYPE = 59;
  int AT = 60;
  int PN_CHARS_BASE = 61;
  int PN_CHARS_U = 62;
  int PN_CHARS = 63;
  int PN_PREFIX = 64;
  int PN_LOCAL = 65;
  int VARNAME = 66;
  int UNKNOWN = 67;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"!\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"<-\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "\"a\"",
    "\"@prefix\"",
    "\"@base\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<DIGITS>",
    "<HEX>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"=>\"",
    "\"$\"",
    "\"?\"",
    "\"~\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\\"",
    "\"^^\"",
    "\"@\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
