#!/bin/bash

function execOne
{
    local datafile="$1"
    local queryfile="$2"
    local label="$3"
    echo "# -------- $label"
    if true
	then
## 	echo "# Data -------------------------------------"
## 	turtle "$1"2 3 4 5 6 7
	echo "# Query ------------------------------------"
	qparse --num --print=query "--query=$2"
	echo "# Results ----------------------------------"
	fi
    
    arq --engine=ref "--data=$1" "--query=$2"
    echo
}

for N in 1 2 3 4 5 6 7
do

  Q1="Q-notexists-$N.arq"
  Q2="Q-minus-$N.arq"

  [ ! -e "$Q1" ] && { echo "Not found: $Q1" 1>&2 ; continue ; }
  [ ! -e "$Q2" ] && { echo "Not found: $Q2" 1>&2 ; continue ; }

  execOne D1.ttl $Q1 "Query $N : NOT EXIST"
  execOne D1.ttl $Q2 "Query $N : MINUS"

  done
