<html>
<head>
<title>the Assembler howto</title>

<link rel="stylesheet" type="text/css" href="../styles/doc.css" />
<link rel="stylesheet" class="text/css" href="assembler-style.css" />

<script type="text/javascript" src="library.js">
</script>

</head>
<body>

<a href="javascript:allAsCondensed()">
&nabla; Switch Schema Display To Condensed
</a>

<a href="javascript:allAsN3()">
&nabla; Switch Schema Display To N3
</a>

<a href="javascript:printCurrentDisplay()">
&nabla; Print Current Display
</a>

<h1>introduction</h1>

<p>
This document describes how to use the Assembler classes to construct models 
-- and other things -- from RDF descriptions that use the 
Jena Assembler vocabulary. That vocabulary is available in
<a href="vocab.n3">ja-vocabulary.n3</a> as an RDFS schema
with conventional prefix <code>ja</code> for the URI
<code>http://jena.hpl.hp.com/2005/11/Assembler#</code>;
the class <code>JA</code> is its Jena Java rendition.
</p>

<p>The examples used in this document are extracted from
the examples file <a href="examples.n3">examples.n3</a>.
The pieces of RDF/OWL schema are extracted from the
ja-vocabulary file and can be viewed as N3 or in a
condensed notation of the form:
</p>

<pre>
class ClassName [subClassOf SuperClasses]
  domainOf PropertyName [withRange RangeClasses] [Cardinality] ...
</pre>

<p>The property names selected are those which are the "declared
properties" (as per Jena's <code>listDeclaredProperties</code>
method) of the class. Only the most specialised superclasses and
rangeclasses are shown, so (for example) <code>rdf:Resource</code>
typically won't appear.
</p>

<h2>overview</h2>

<p>An Assembler specification is a Resource in some RDF Model. The
properties of that Resource describe what kind of object is to be
assembled and what its components are: for example, an InfModel
is constructed by specifying a base model and a reasoner. The
specifications for the components are themselves Assembler specifications
given by other Resources in the same Model.For example, to specify a 
memory model with data loaded from a file:
</p>

<div class='insert-example' root='eg:opening-example' source='examples'>example 1 goes here</div>

<p>
The rdf:type of eg:model specifies that the constructed Model is to
be a Jena memory-based model. The ja:content property specifies
that the model is to be loaded with the content of the resource
file:Data/example.n3. The content handler guesses from the ".n3" suffix
that this file is to be read using the Jena N3 reader.
</p>

<p>
Unless otherwise specified by an application, Assembler specifications 
are interpreted after adding in the JA schema and doing (limited) RDFS inference. 
In the example above, eg:model has to be given an explicit type, 
but the externalContent bnode is implicitly typed by the domain of 
ja:externalContent. In this document, we will usually leave out 
inferrable types. 
</p>

<p>
We can construct our example model from the specification like this
(you may need to tweak the filename to make this work in your
environment):
</p>

<pre>
Model spec = FileManager.get().loadModel( "examples.n3" );
Resource root = spec.createResource( spec.expandPrefix( "eg:opening-example" ) );
Model m = Assembler.general.openModel( root );
</pre>

<p>The model is constructed from the "root resource", 
<code>eg:opening-example</code> in our example. <code>general</code>
knows how to create all the kinds of objects -- not just Models --
that we describe in the next sections. 
</p>

<h1>specifications common to all models</h1>

<p>Assembler specifications can describe many kinds of models:
memory, inference, database, ontology, and file-backed.
All of these model specifications share a set of base properties
for attaching content, prefix mappings, and reification modes.
</p>

<div class='insert-class' root='ja:Loadable' source='vocab'>ja:Loadbale goes here</div>
<div class='insert-class' root='ja:Model' source='vocab'>ja:Model goes here</div>

<p>All of a model's <code>ja:content</code> property values are
interpreted as specifying <code>Content</code> objects and a single
composite <code>Content</code> object is constructed and used
to initialise the model. 
See <a href="#spec-content">Content</a> for the description of Content
specifications. For example:</p>

<div class='insert-example' root='eg:common-example' source='examples'>example 1 goes here</div>

<p>
The model constructed for <code>eg:A</code> will be loaded with the
contents of <code>Data/A.n3</code>, <code>Data/B.rdf</code>,
and <code>http://somewhere/RDF/ont.owl</code>. If the model supports
transactions, then the content is loaded inside a transaction; if the
load fails, the transaction is aborted, and a
<code>TransactionAbortedException</code> thrown. 
If the content has any prefix mappings, then they are also added 
to the model.
</p>

<p>All of a model's <code>ja:includes</code>, <code>ja:prefix</code>,
and <code>ja:namespace</code> properties are
interpreted as specifying a <code>PrefixMapping</code> object and
a single composite <code>PrefixMapping</code> is constructed and used
to set the prefixes of the model. 
See <a href="#spec-prefix-mapping">PrefixMapping</a> for the description of Content
specifications.</p>

<p>A model may have a single <code>ja:reificationMode</code>
property whose value must be one of the constants <code>ja:standard</code>,
<code>ja:convenient</code>, or <code>ja:minimal</code>. The
model's reification mode is set accordingly, if possible. 
<span class='note'>Not implemented yet.</span></p>

<h2><a name="spec-content">content</a></h2>

A Content specification describes content that can be used to fill
models. Content can be external (files and URLs) or literal 
(strings in the specification) or quotations (referring to RDF which
is part of the specification).

<div class='insert-class' root='ja:Content' source='vocab'>ja:Content goes here</div>

<p>
A <code>ja:Content</code> specification may have zero or more 
<code>ja:externalContent</code> property values. These are URI
resources naming an external (file or http etc) RDF object. 
The constructed Content object contains the union of the values of
all such resources. For example:
</p>

<div class='insert-example' root='eg:external-content-example' source='examples'>example 1 goes here</div>

<p>The string literal value of the any <code>ja:literalContent</code>
properties is interpreted as RDF in an appropriate language. The constructed
Content object contains that RDF. The language is either specified by an
explicit <code>ja:contentEncoding</code> property value, or guessed from
the content of the string. The only encodings permitted are "N3" and "RDF/XML". 
For example:
</p>

<div class='insert-example' root='eg:literal-content-example' source='examples'>example 1 goes here</div>

<p>The literal content is wrapped so that prefix declarations for 
<b>rdf</b>, <b>rdfs</b>, <b>owl</b>, <b>dc</b>, and <b>xsd</b>
apply before interpretation.</p>

<p>The property values of any <code>ja:quotedContent</code> properties
should be resources. The subgraphs rooted at those resources (using the
algorithm from <code>ResourceUtils.reachableClosure()</code>) are added
to the content.
</p>

<h2>RDB models and Connections</h2>

<p>
The description of an RDB model requires its name and a description of
the JDBC connection for the database the model is in. For example:
</p>

<div class='insert-example' root='eg:database-example' source='examples'>example 1 goes here</div>

<div class='insert-class' root='ja:RDBModel' source='vocab'>ja:RDBModel goes here</div>
<div class='insert-class' root='ja:Connectable' source='vocab'>ja:Connectable goes here</div>
<div class='insert-class' root='ja:NamedModel' source='vocab'>ja:NamedModel goes here</div>

<p><code>ja:RDBModel</code> is a subclass of <code>ja:NamedModel</code>
and shares the <code>ja:ModelName</code> property value naming the model
within the database.</p>

<p>The mandatory unique property value of <code>ja:connection</code> 
specifies the connection to the database to be used.
</p>

<p>The description of a connection requires the database name and type
and the user name and password. If the username and password are not
specified, <code>Assembler.general</code> will default them, normally
to the values of the system properties <code>jena.dbUser</code> and
<code>jena.dbPassword</code>.
</p>

<div class='insert-class' root='ja:Connection' source='vocab'>ja:Connection goes here</div>

<p>The <code>ja:dbURL</code> property value specifies the
URL of the database to be connected to. If it is ommitted, the 
<code>ja:dbURLProperty</code> value is the name of a Java system
property whose value is the URL of the database.</p>

<p>The <code>ja:dbType</code> property value
specifies the type of the database as a string. If it is omitted, the
<code>ja:dbTypeProperty</code> value is the name of a Java
system property whose value is the database type.</p>

<p>The unique <code>ja:dbUser</code> property value is a string
literal whose value is the name of the user connecting to the
database. If it is omitted, the value of the <code>ja:dbUserProperty</code>
is the name of a Java system property containing the user name.</p>

<p>The unique <code>ja:dbPassword</code> property value is the
password of the user connecting to the database. If it is omitted,
the value of the <code>ja:dbPasswordProperty</code> is the name
of a Java system property whose value is the password.</p>

<h2>file models</h2>

<p>A FileModel specification builds a memory model that is backed by a file.
By "backed", we mean that the model is loaded from that file and written
back to the file when (if) it is closed. Furthermore, the model (weakly)
supports transactions.
</p>

<div class='insert-example' root='eg:fileModel-example-1' source='examples'>FileModel example goes here</div>

<p>
Here, the model is read from (and written to) the file <code>/tmp/simple</code>.
Directory names are given as resources (not literals) and of course file names
are system dependant -- this is what one might see on a Unix system. If the
directory name is to be shared by several different FileModels, it can be useful
to give it a namespace prefix so that it can be changed in one place as
necessary.
</p>

<div class='insert-example' root='eg:fileModel-example-2' source='examples'>FileModel example goes here</div>

<p>
Model names can be <i>mapped</i> to allow them to be URIs without the
/s in URIs being taken as directory separators. Here, the base file name
will be <code>FileModels/http_C_S_Ssomewhere.org_Sstuff.n3</code>. The
encoding is not pretty, but is sufficient for simple URIs.
</p>

<div class='insert-class' root='ja:FileModel' source='vocab'>ja:FileModel goes here</div>

<p>The <code>ja:directory</code> property specifies the directory in which the
model file is located. The <code>ja:modelName</code> property specifies the name of
the file within that directory.
</p>

<p>The optional unique property <code>ja:fileEncoding</code> has as its value
a string which is the name of the encoding language of the model (ie one of
RDF/XML or N3, etc). If it is omitted, the language is guessed from the suffix
of the filename (as per <code>FileUtils.guessLang()</code>).
</p>

<p>If the optional unique property <code>ja:mapName</code> has the value
<code>ja:true</code>, then the name of the model is <i>mapped</i> by replacing
any _, /, or : characters by the escape sequences __, _S, or _C. This
translation (which is the same one done by <code>FileGraphMaker</code> for
<code>FileModelMaker</code>) allows URIs to be used as model names without
conflicting with the filesystems use of / characters.
</p>

<h2>inference models and reasoners</h2>

<p>Inference models are specified by supplying a description of the
reasoner that is used by the model and (optionally) a base model to
reason over. For example:</p>

<div class='insert-example' root='eg:inference-example' source='examples'>inference example goes here</div>

<p>describes an inference model that uses RDFS reasoning. The 
<i>reasonerURL</i> property value is the URI used to identify the
reasoner (it is the value of the Jena constant 
<code>RDFSRuleReasonerFactory.URI</code>). The base model is
specified as a memory model; if it is left out, an empty memory
model is used. Of course, you can specify a database model as a base
model:
</p>

<div class='insert-example' root='eg:db-inference-example' source='examples'>inference example goes here</div>

<p>The same reasoner as used as in the previous example, but now the
base model is a database specified in the same way as our earlier example.
</p>

<p>Because Jena's access to external reasoners goes through the same API as
for its internal reasoners, you can access a DIG reasoner (such as Pellet
running as a server) using an Assembler specification:

<div class='insert-example' root='eg:external-inference-example' source='examples'>external inference example here</div>

If there's a DIG server running locally on port 2004, this specification
will create a DIG inference model that uses it.
</p>

<p>The internal rule reasoner can be supplied with rules written inside
the specification, or outside from some resource (file or http: URL):

<div class='insert-example' root='eg:rule-inference-example' source='examples'>rule inference example goes here</div>

This reasoner will infer a type declaration from a use of a property.
<span class='note'>say something about the prefix <i>my</i>.</span>

</p>

<div class='insert-class' root='ja:InfModel' source='vocab'>ja:InfModel goes here</div>
<div class='insert-class' root='ja:ReasonerFactory' source='vocab'>ja:ReasonerFactory goes here</div>
<div class='insert-class' root='ja:HasRules' source='vocab'>ja:HasRules goes here</div>
<p>An InfModel's <code>ja:baseModel</code> property value specifies
the base model for the inference model; if omitted, an empty memory model is
used. </p> 

<p>An InfModel's <code>ja:Reasoner</code> property value specifies
the Reasoner for this inference model; if omitted, a GenericRuleReasoner
is used.
<span class='note'>FIX: now a reasonerFactory.</span>
</p>

<p>A Reasoner's optional <code>ja:schema</code> property
specifies a Model which contains the schema for the reasoner to
be bound to. If omitted, no schema is used.
<span class='note'>Not implemented yet.</span></p>

<p>If the Reasoner is a GenericRuleReasoner, it may have any of the
RuleSet properties <code>ja:rules</code>, <code>ja:rulesFrom</code>,
or <code>ja:rule</code>. The rules of the implied <code>RuleSet</code>
are added to the <code>Reasoner</code>.
</p>

<h3>rulesets</h3>

<span class='note'>RuleSet examples go here.</span>

<p>
A <code>RuleSet</code> specification allows rules (for ReasonerFactories)
to be specified inline, elsewhere in the specification model, or in an external
resource.
</p>

<div class='insert-class' root='ja:RuleSet' source='vocab'>ja:RuleSet goes here</div>

<p>The optional repeatable property <code>ja:rule</code> has as its value
a literal string which is the text of a Jena rule or rules. All those rules
are added to the <code>RuleSet</code>.</p>

<p>The optional repeatable property <code>ja:rulesFrom</code> has as its value
a resource whose URI identifies a file or other external entity that can be
loaded as Jena rules. All those rules are added to the <code>RuleSet</code>.</p>

<p>The optional repeatable property <code>ja:rules</code> has as its value
a resource which identifies another <code>RuleSet</code> in the specification model.
All those rules from that <code>RuleSet</code> are added to this <code>RuleSet</code>.</p>

<h2>ontology models</h2>

<p>
Ontology models can be specified in several ways. The simplest is to use
the name of an OntModelSpec from the Java OntModelSpec class:
</p>

<div class='insert-example' source='examples' root='eg:simple-ont-example'>simple-ont-example</div>

<p>This constructs an <code>OntModel</code> with an empty base model
and using the OWL_DL language and the full rule reasoner. All of the
OntModelSpec constants in the Jena implementation are available in this way.
A base model can be specified:
</p>

<div class='insert-example' source='examples' root='eg:base-ont-example'>simple-ont-example</div>

<p>The OntModel has a base which is a memory model loaded with the contents
of <i>http://jena.hpl.hp.com/some-jena-data.rdf</i>. Since the ontModelSpec
was omitted, it defaults to <code>OWL_MEM_RDFS_INF</code> - the same default
as <code>ModelFactory.createOntologyModel()</code>.
</p>

<div class='insert-class' root='ja:OntModel' source='vocab'>ja:OntModel goes here</div>
<div class='insert-class' root='ja:OntModelSpec' source='vocab'>ja:OntModelSpec goes here</div>
<p><code>OntModel</code> is a subclass of <code>InfModel</code>, and the
<code>ja:baseModel</code> property means the same thing.
</p>

<p>The <code>OntModelSpec</code> property value is a resource. If that
resource has any properties in the specification model, it is interpreted 
as an OntModelSpec description;
otherwise the local name of the value is interpreted as the name of an
OntModelSpec constant (looked up by reflection).</p>

<p>An <code>OntModelSpec</code> has several possible properties.

<ul>
<li><code>ja:importSource</code>:
The value of this optional unique property is a <code>ModelSource</code>
description which describes where imports are obtained from.
<span class='note'>Description incomplete - note this replaces the ImportMaker
from the ModelSpec code.</span></li>

<li><code>ja:documentManager</code>:
This value of this optional unique property is a DocumentManager specification.
If absent, the default document manager is used.

<li><code>ja:reasonerURL</code>:
The value of this optional unique property is the URL of the ReasonerFactory
to be used to construct this OntModelSpec's reasoner. 
<span class='note'>Fix up WRT InfModels;m note what happens to rulesets.</span></li>

<li><code>ja:ontLanguage</code>:
The value of this optional unique property is one of the values in the
<code>ProfileRegistry</code> class which identifies the ontology language
of this <code>OntModelSpec</code>:

    <ul>
    <li>OWL: http://www.w3.org/2002/07/owl#
    <li>OWL DL: http://www.w3.org/TR/owl-features/#term_OWLDL
    <li>OWL Lite: http://www.w3.org/TR/owl-features/#term_OWLLite
    <li>RDFS: http://www.w3.org/2000/01/rdf-schema#
    <li>DAML: http://www.daml.org/2001/03/daml+oil#
    </ul>
    
</li>
</ul>
</p>

<h2>document managers</h2>

<p>An <code>OntDocumentManager</code> can be specified by a
<code>ja:DocumentManager</code> specification which describes the
<code>OntDocumentManager</code>'s file manager and policy settings.
</p>

<div class='insert-example' source='examples' root='eg:document-manager-example'>document-manager-example</div>

<p>In this example, <code>eg:document-manager-example</code> is a 
<code>ja:DocumentManager</code> specification. It has its own 
<code>FileManager specification</code>, the object of the
<code>ja:fileManager property</code>; that <code>FileManager</code>
has a location mapper, <code>eg:mapper</code>, that maps a single
filename.</p>

<p>
The document manager also has an additional property to link it to
document manager meta-data: the sub-model of the assembler specification
reachable from <code>eg:document-manager-example</code> is passed to
the document manager when it is created. For the meanings of the 
<code>dm:</code> properties, see the Jena ontology documentation and
the ontology.rdf ontology.
</p>

<div class='insert-class' root='ja:DocumentManager' source='vocab'>ja:DocumentManager goes here</div>

<p>
The <code>ja:fileManager</code> property value, if present, has as its object
a <code>ja:FileManager</code> specification; the constructed document manager
is given a new file manager constructed from that specification. If there is no
<code>ja:fileManager</code> property, then the default <code>FileManager</code>
is used.
</p>

<p>The <code>ja:policyPath</code> property value, if present, should be a string
which is a path to policy files as described in the Jena ontology documentation.
If absent, the usual default path is applied.
</p>

<p>If the sub-model of the assembler specification reachable from the 
DocumentManager resource contains any OntDocumentManager DOC_MGR_POLICY
or ONTOLOGY_SPEC objects, they will be interpreted by the constructed
document manager object.
</p>

<div class='insert-class' root='ja:FileManager' source='vocab'>ja:FileManager goes here</div>

<p>A <code>ja:FileManager</code> object may have a <code>ja:locationMapper</code>
property value which identifies the specification of a <code>LocationMapper</code>
object initialising that file manager.
</p>

<div class='insert-class' root='ja:LocationMapper' source='vocab'>ja:LocationMapper goer goes here</div>

<p>
A <code>ja:LocationMapper</code> object may have <code>lm:mapping</code>
property values, describing the location mapping, as described in the
FileManager documentation. (Note that the vocabulary for those items is
in a different namespace than the JA properties and classes.)</p>

<h2>union models</h2>

<p>
Union models can be constructed from any number of submodels and a
single <i>root</i> model. The root model is the one written to when
the union model is updated; the submodels are untouched.
</p>

<p><span class='note'>example needed here.</span></p>

<div class='insert-class' root='ja:UnionModel' source='vocab'>ja:UnionModel goes here</div>

<p>
If the single <code>ja:rootModel</code> property is present, its value
describes a model to use as the root model of the union. All updates to the
union are directed to this root model. If no root model is supplied, the
union is given an <i>immutable</i>, <i>empty</i> model as its root.
</p>

<p>
Any <code>ja:subModel</code> property values have objects describing 
the remaining sub-models of the union. The order of the sub-models in the
union is <i>undefined</i> (which is why there's a special rootModel
property).
</p>

<h2>prefix mappings</h2>

<p>The PrefixMappings of a model may be set from PrefixMapping specifications.
<span class='note'>examples please.</span></p>

<div class='insert-class' root='ja:PrefixMapping' source='vocab'>ja:PrefixMapping goes here</div>
<div class='insert-class' root='ja:SinglePrefixMapping' source='vocab'>ja:SinglePrefixMapping</div>

<p>The <code>ja:includes</code> property allows a PrefixMapping to include the
content of other specified PrefixMappings.
</p>

<p>The <code>ja:prefix</code> and <code>ja:namespace</code> properties
allow the construction of a single element of a prefix mapping by specifying
the prefix and namespace of the mapping.</p>

<h2>other Assembler directives</h2>

<p>There are two more <code>Assembler</code> directives that can be 
used in an Assembler specification: the <i>assembler</i> and <i>imports</i>
directives.</p>

<h3>assembler</h3>

<p>A specification may contain statements of the form:

<blockquote>
<code>someResource ja:assembler "some.Assembler.class.name"</code>
</blockquote>

<p>
When <code>someResource</code> is used as the type of a root object,
the AssemblerGroup that processes the description will use an instance
of the Java class named by the object of the statement. That class
must implement the <code>Assembler</code> interface. See
<a href="#loading-assembler-classes">loading assembler classes</a> 
for more details.
</p>

<h3>imports</h3>

<p>If a specification contains statements of the form:

<blockquote>
<code>anyResource owl:imports someURL</code>
</blockquote>

or, equivalently, 

<blockquote>
<code>anyResource ja:imports someURL</code>
</blockquote>

then the specification is regarded as also containing the contents of the
RDF at <code>someURL</code>. That RDF may in turn contain 
<code>imports</code> referring to other RDF. 
<span class='note'>Cycle detection is not yet implemented. The loaded
models are cached; cache control is not implemented yet.</span>
</p>

<h1>inside Assemblers</h1>

<p><code>Assembler.general</code> is a particular implementation of
the <code>Assembler</code> interface. An <code>Assembler</code> knows
how to build the objects -- not just models -- described by an Assembler
specification. The normal route into an Assembler is through the method:

<ul>
<li>open( Resource root ) &rarr; Object</li>
</ul>

The Assembler inspects the <code>root</code> resource properties and
decides whether it can build an object with that description. If not,
it throws an exception. Otherwise, it constructs and returns a suitable
object.
</p>

<p>Since the creation of Models is the reason for the existance of
Assemblers, there is a convenience wrapper method:

<ul>
<li>openModel( Resource root ) &rarr; Model</li>
</ul>

which constructs the object and checks that it's a Model before
returning it.
</p>

<p>When an <code>Assembler</code> requires sub-objects (for example,
when an InfModel Assembler requires a Reasoner object), it uses the
method:

<ul>
<li>open( Assembler sub, Resource root ) &rarr; Model</li>
</ul>

passing in a suitable Assembler object. In fact the standard implementation
of <code>open(root)</code> is just 

<ul>
<li>open( this, root )</li>
</ul>

passing in itself as the sub-assembler and having 
<code>open(Assembler,Resource)</code> be the place where
all the work is done. (Amongst other things, this makes testing
easier.)
</p>

<p>When working with named persistent objects (typically database models),
sometimes you need to control whether new objects should be constructed
or old models can be reused. There is an additional method

<ul>
<li>open( Assembler sub, Resource root, Mode mode )</li>
</ul>

where the <code>Mode</code> argument controls the creation (or not)
of persistent models. The mode is passed down to all sub-object
creation. The standard implementation of <code>open(sub,root)</code>
is just:

<ul>
<li>open( sub, root, Mode.DEFAULT )</li>
</ul>

A <code>Mode</code> object has two methods:

<ul>
<li>permitCreateNew( Resource root, String name )</li>
<li>permitUseExisting( Resource root, String name )</li>
</ul>

<code>root</code> is the root resource describing the object to be
created or reused, and <code>name</code> is the name given to it.
The result is <code>true</code> iff the permission is granted.
<code>Mode.DEFAULT</code> permits the reuse of existing objects
and denies the creation of new ones.
</p>

<p>
There are four <code>Mode constants:</code>

<ul>
<li>Mode.DEFAULT - reuse existing objects</li> 
<li>Mode.CREATE - create missing objects</li>
<li>Mode.REUSE - reuse existing objects</li>
<li>Mode.ANY - reuse existing objects, create missing ones</li>
</ul>

Since the <code>Mode</code> methods are passed the resource root and
name, the user can write specialised <code>Mode</code>s that look at
the name or the other root properties to make their decision.
</p>

<p>
Note that the Modes only apply to persistent objects, so <i>eg</i>
MemoryModels or PrefixMappings ignore their Mode arguments.
</p>

<h1>basic assemblers</h1>

<p>
There is a family of <i>basic assemblers</i>, each of which knows how to
assemble a specific kind of object so long as they're given an
Assembler that can construct their sub-objects. There are defined constants
in <code>Assembler</code> for (an instance of) each of these basic
assembler classes. 
</p>

<table class='framed' align='center'>
<thead>
    <tr><th>produces</th><th>Class</th><th>Type</th><th>constant</th></tr>
</thead>
<tbody>
<tr>
    <td>default models</td>
    <td>DefaultModelAssembler</td>
    <td>ja:DefaultModel</td>
    <td>defaultModel</td>
</tr>
<tr>
    <td>memory models</td>
    <td>MemoryModelAssembler</td>
    <td>ja:MemoryModel</td>
    <td>memoryModel</td>
</tr>
<tr>
    <td>inference models</td>
    <td>InfModelAssembler</td>
    <td>ja:InfModel</td>
    <td>infModel</td>
</tr>
<tr>
    <td>RDB models</td>
    <td>RDBModelAssembler</td>
    <td>ja:RDBModel</td>
    <td>rdbModel</td>
</tr>
<tr>
    <td>reasoners</td>
    <td>ReasonerAssembler</td>
    <td>ja:Reasoner</td>
    <td>reasoner</td>
</tr>
<tr>
    <td>connection descriptions</td>
    <td>ConnectionAssembler</td>
    <td>ja:Connection</td>
    <td>connection</td>
</tr>
<tr>
    <td>content</td>
    <td>ContentAssembler</td>
    <td>ja:Content</td>
    <td>content</td>
</tr>
<tr>
    <td>ontology models</td>
    <td>OntModelAssembler</td>
    <td>ja:OntModel</td>
    <td>ontModel</td>
</tr>
<tr>
    <td>rules</td>
    <td>RuleSetAssembler</td>
    <td>ja:RuleSet</td>
    <td>rules</td>
</tr>
<tr>
    <td>union models</td>
    <td>UnionModelAssembler</td>
    <td>ja:UnionModel</td>
    <td>unionModel</td>
</tr>
<tr>
    <td>prefix mappings</td>
    <td>PrefixMappingAssembler</td>
    <td>ja:PrefixMapping</td>
    <td>prefixMapping</td>
</tr>
<tr>
    <td>file models</td>
    <td>FileModelAssembler</td>
    <td>ja:FileModel</td>
    <td>fileModel</td>
</tr>
</tbody>
</table>

<p>
<code>Assembler.general</code> is an <i>assembler group</i>,
which ties together those basic assemblers. <code>general</code>
can be extended by Jena coders if required. Jena components that
use Assembler specifications to construct objects will use
<code>general</code> unless documented otherwise.
</p>

<p>
In the remaining sections we will discuss the <code>Assembler</code>
classes that return non-Model objects and conclude with a description
of <code>AssemblerGroup</code>.
</p>

<h2>basic assembler ContentAssembler</h2>

<p>The ContentAssembler constructs Content objects (using the 
<code>ja:Content</code> vocabulary) used to supply
content to models. A Content object has the method:

<ul>
<li>fill( Model m ) &rarr; m</li>
</ul>

Invoking the <code>fill</code> method adds the represented content to
the model. The supplied ModelAssemblers automatically apply 
the <code>Content</code> objects corresponding to 
<code>ja:content</code> property values.
</p>

<h2>basic assembler ConnectionAssembler</h2>

<p>A ConnectionAssembler constructs ConnectionDescriptions 
according to the specification. An ConnectionDescription 
retains the information required to make a database connection,
can constructs that connection on demand.</p>

<p>When a ConnectionAssembler is constructed, it may optionally
be given a Resource describing (using the JA vocabulary) default values 
for any of the database properties. When that Assembler is used to 
create a Connection, missing values are filled in from the defaults. 
This allows sensitive information to be left out of the RDF description.
</p>

<p>The ConnectionAssembler embedded in Assembler.general has
defaults taken from the system proeprties <code>jena.dbUser</code>
and <code>jena.dbType</code> (<span class='note'>not implemented yet</span>. 
</p>

<p class='note'>Driver issues? Defaulting the database type?</p>

<h2>basic assembler RulesetAssembler</h2>

<p>A RulesetAssembler generates lists of Jena rules.
</p>

<h2>basic assembler DefaultModelAssembler</h2>

<p>A "default model" is a model of unspecified type which is implemented as
whatever kind the assembler for <code>ja:DefaultModel</code> generates.
The default for a DefaultModel is to create a MemoryModel with no special
properties.
</p>

<h2>AssemblerGroup</h2>

<p>The AssemblerGroup class allows a bunch of other Assemblers to be
bundled together and selected by RDF type. AssemblerGroup implements
Assembler and adds the methods:</p>

<ul>
<li>implementWith( Resource type, Assembler a ) &rarr; this</li>
<li>assemblerFor( Resource type ) &rarr; Assembler</li>
</ul> 

<p>AssemblerGroup's implementation of <code>open(sub,root)</code>
finds the <i>most specific type</i> of <code>root</code> that is a subclass
of <code>ja:Object</code> and looks for the Assembler that has been
associated with that type by a call of <code>implementWith</code>. 
It then delegates construction to that
Assembler, passing <i>itself</i> as the sub-assembler. Hence each
component Assembler only needs to know how to assemble its own
particular objects.
</p>

<p>The <code>assemblerFor</code> method returns the assembler associated
with the argument type by a previous call of <code>implementWith</code>,
or <code>null</code> if there is no associated assembler.</p>

<h3><a id="loading-assembler-classes">loading assembler classes</a></h3>

<p>
AssemblerGroups implement the <code>ja:assembler</code> functionality.
The object of an <code>(type ja:assembler "ClassName")</code> statement
is a string which is taken as the name of an <code>Assembler</code>
implementation to load. An instance of that class is associated with
<code>type</code> using <code>implementWith</code>.
</p>

<p>If the class has a constructor that takes a single <code>Resource</code>
object, that constructor is used to initialise the class, passing in the
<code>type</code> subject of the triple. Otherwise the no-argument
constructor of the class is used.
</p>

</body>
</html>
