PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND("{1:'one', 2:'two', '02'^^<http://www.w3.org/2001/XMLSchema#integer>: 'also two'}"^^cdt:Map AS ?map)
	FILTER(cdt:get(?map, 1) = "one")
	FILTER(cdt:get(?map, 2) = "two")
	FILTER(cdt:get(?map, "02"^^xsd:integer) = "also two")
}
