PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( cdt:Map(1,2, ?unbound, 4, 5,6) AS ?map )
	FILTER( ?map = "{1:2, 5:6}"^^cdt:Map )
}
