PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( cdt:Map("hello"@en,"one", "hello", "also one") AS ?map )
	FILTER( ?map = "{'hello'@en:'one', 'hello':'also one'}"^^cdt:Map )
}
