PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

# IRIs as map values cannot be compared to literals
ASK {
	BIND( "{1: <http://example.org/b>}"^^cdt:Map AS ?map1 )
	BIND( "{1: 42}"^^cdt:Map AS ?map2 )
	BIND( (?map1 <= ?map2 ) AS ?result )
	FILTER( ! BOUND(?result) )
}
