PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( ( "{1:42, 2:43}"^^cdt:Map > "{1:42}"^^cdt:Map ) AS ?result )
	FILTER( BOUND(?result) )
	FILTER( ?result = true )
}
