PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( "{1: null, 2: 'two'}"^^cdt:Map AS ?map1 )
	BIND( "{3: 'three'}"^^cdt:Map AS ?map2 )
	BIND( cdt:merge(?map1, ?map2) AS ?merged )

	FILTER( cdt:size(?merged) = 3 )

	FILTER( cdt:containsKey(?merged,1) )
	BIND( cdt:get(?merged,1) AS ?x )
	FILTER( ! BOUND(?x) )

	FILTER( cdt:get(?merged,2) = "two" )

	FILTER( cdt:get(?merged,3) = "three" )
}
