PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>

ASK {
	BIND( "{}"^^cdt:Map AS ?mapIn )
	BIND( cdt:put(?mapIn, 1, ?unbound) AS ?mapOut )

	FILTER( BOUND(?mapOut) )    # check that there was no error
	FILTER( cdt:size(?mapOut) = 1 )
	FILTER( cdt:containsKey(?mapOut,1) )
	BIND( cdt:get(?mapOut,1) AS ?value )
	FILTER( ! BOUND(?value) )
}
