PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( "{1:'one', 2:'two'}"^^cdt:Map AS ?mapIn )
	BIND( cdt:put(?mapIn, "01"^^xsd:integer, "alsoOne") AS ?mapOut )

	FILTER( BOUND(?mapOut) )    # check that there was no error
	FILTER( ?mapOut = "{1:'one', '01'^^<http://www.w3.org/2001/XMLSchema#integer>:'alsoOne', 2:'two'}"^^cdt:Map )
}
