/* Generated By:JavaCC: Do not edit this line. SPARQLParserConstants.java */
/*
 * (c) Copyright 2004, 2005, 2006, 2007 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package com.hp.hpl.jena.sparql.lang.sparql ;

public interface SPARQLParserConstants {

  int EOF = 0;
  int WS = 6;
  int SINGLE_LINE_COMMENT = 7;
  int Q_IRIref = 8;
  int QNAME_NS = 9;
  int QNAME_LN = 10;
  int BLANK_NODE_LABEL = 11;
  int VAR1 = 12;
  int VAR2 = 13;
  int LANGTAG = 14;
  int A2Z = 15;
  int A2ZN = 16;
  int KW_A = 17;
  int BASE = 18;
  int PREFIX = 19;
  int SELECT = 20;
  int DISTINCT = 21;
  int REDUCED = 22;
  int DESCRIBE = 23;
  int CONSTRUCT = 24;
  int ASK = 25;
  int LIMIT = 26;
  int OFFSET = 27;
  int ORDER = 28;
  int BY = 29;
  int ASC = 30;
  int DESC = 31;
  int NAMED = 32;
  int FROM = 33;
  int WHERE = 34;
  int AND = 35;
  int GRAPH = 36;
  int OPTIONAL = 37;
  int UNION = 38;
  int FILTER = 39;
  int BOUND = 40;
  int STR = 41;
  int DTYPE = 42;
  int LANG = 43;
  int LANGMATCHES = 44;
  int IS_URI = 45;
  int IS_IRI = 46;
  int IS_BLANK = 47;
  int IS_LITERAL = 48;
  int REGEX = 49;
  int SAME_TERM = 50;
  int TRUE = 51;
  int FALSE = 52;
  int DIGITS = 53;
  int INTEGER = 54;
  int DECIMAL = 55;
  int DOUBLE = 56;
  int INTEGER_POSITIVE = 57;
  int DECIMAL_POSITIVE = 58;
  int DOUBLE_POSITIVE = 59;
  int INTEGER_NEGATIVE = 60;
  int DECIMAL_NEGATIVE = 61;
  int DOUBLE_NEGATIVE = 62;
  int EXPONENT = 63;
  int QUOTE_3D = 64;
  int QUOTE_3S = 65;
  int ECHAR = 66;
  int STRING_LITERAL1 = 67;
  int STRING_LITERAL2 = 68;
  int STRING_LITERAL_LONG1 = 69;
  int STRING_LITERAL_LONG2 = 70;
  int LPAREN = 71;
  int RPAREN = 72;
  int NIL = 73;
  int LBRACE = 74;
  int RBRACE = 75;
  int LBRACKET = 76;
  int RBRACKET = 77;
  int ANON = 78;
  int SEMICOLON = 79;
  int COMMA = 80;
  int DOT = 81;
  int EQ = 82;
  int NE = 83;
  int GT = 84;
  int LT = 85;
  int LE = 86;
  int GE = 87;
  int BANG = 88;
  int TILDE = 89;
  int COLON = 90;
  int SC_OR = 91;
  int SC_AND = 92;
  int PLUS = 93;
  int MINUS = 94;
  int STAR = 95;
  int SLASH = 96;
  int DATATYPE = 97;
  int AT = 98;
  int NCCHAR1P = 99;
  int NCCHAR1 = 100;
  int NCCHAR = 101;
  int NCNAME_PREFIX = 102;
  int NCNAME = 103;
  int VARNAME = 104;
  int UNKNOWN = 105;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME_NS>",
    "<QNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"filter\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "<NCCHAR1P>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
