/* Generated By:JavaCC: Do not edit this line. SSE_ParserCoreConstants.java */
/*
 * (c) Copyright 2007 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package com.hp.hpl.jena.sparql.sse.parser ;

public interface SSE_ParserCoreConstants {

  int EOF = 0;
  int WS = 1;
  int SINGLE_LINE_COMMENT1 = 2;
  int SINGLE_LINE_COMMENT2 = 3;
  int IRIref = 4;
  int PNAME = 5;
  int BLANK_NODE_LABEL = 6;
  int VAR1 = 7;
  int VAR2 = 8;
  int DIGITS = 9;
  int INTEGER = 10;
  int DECIMAL = 11;
  int DOUBLE = 12;
  int EXPONENT = 13;
  int QUOTE_3D = 14;
  int QUOTE_3S = 15;
  int ECHAR = 16;
  int STRING_LITERAL1 = 17;
  int STRING_LITERAL2 = 18;
  int STRING_LITERAL_LONG1 = 19;
  int STRING_LITERAL_LONG2 = 20;
  int LPAREN = 21;
  int RPAREN = 22;
  int LBRACE = 23;
  int RBRACE = 24;
  int LBRACKET = 25;
  int RBRACKET = 26;
  int HOOK = 27;
  int DATATYPE = 28;
  int LANGTAG = 29;
  int AT = 30;
  int A2Z = 31;
  int A2ZN = 32;
  int PN_CHARS_BASE = 33;
  int PN_CHARS_U = 34;
  int PN_CHARS = 35;
  int PN_PREFIX = 36;
  int PN_LOCAL = 37;
  int VARNAME = 38;
  int WORD = 39;
  int OP = 40;
  int UNKNOWN = 41;

  int DEFAULT = 0;
  int LITERAL = 1;

  String[] tokenImage = {
    "<EOF>",
    "<WS>",
    "<SINGLE_LINE_COMMENT1>",
    "<SINGLE_LINE_COMMENT2>",
    "<IRIref>",
    "<PNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"^^\"",
    "<LANGTAG>",
    "\"@\"",
    "<A2Z>",
    "<A2ZN>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<WORD>",
    "<OP>",
    "<UNKNOWN>",
  };

}
