# ==== Ex 1 : Names of proteins with a gene with a specific name or synonym
# 
# SELECT 
#   ?protein, ?name 
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :name ?name] AND 
#   [?protein :encodedBy ?gene] AND 
#   [?gene :name "CRB"] 
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf

PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :      <urn:lsid:uniprot.org:ontology:>
SELECT  ?protein ?name
WHERE
  { ?protein  rdf:type    :Protein ;
              :name       ?name ;
              :encodedBy  ?gene .
    ?gene     :name       "CRB" .
  }
