# ==== Ex 2 :Ranges of transmembrane regions
# 
# SELECT 
#   ?protein, ?begin, ?end 
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :annotation ?annotation] AND
#   [?annotation rdf:type :Transmembrane_Annotation] AND 
#   [?annotation  :range ?range] AND 
#   [?range :begin ?begin] AND  -- Note: Should use MAYBE...
#   [?range :end ?end] 
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf

PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :      <urn:lsid:uniprot.org:ontology:>
SELECT  ?protein ?begin ?end
WHERE
  { ?protein  rdf:type     :Protein ;
              :annotation  ?annotation .
    ?annotation  rdf:type  :Transmembrane_Annotation .

    # As given
    ?annotation  :range ?range .
    ?range :begin ?begin .
    ?range :end ?end .
    # Optional
##     OPTIONAL
##       { ?annotation  :range  ?range .
##         ?range    :begin  ?begin ;
##                   :end    ?end .
##       }
  }
