# ==== Ex 2 :Ranges of transmembrane regions

PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :      <urn:lsid:uniprot.org:ontology:>
SELECT  ?protein ?begin ?end
WHERE
{
    ?annotation  rdf:type  :Transmembrane_Annotation .
    ?protein     :annotation  ?annotation .
    ?protein     rdf:type     :Protein .

    # As given
    ?annotation  :range ?range .
    ?range :begin ?begin .
    ?range :end ?end .

    # Optional
##     OPTIONAL
##       { ?annotation  :range  ?range .
##         ?range    :begin  ?begin ;
##                   :end    ?end .
##       }
  }
