# ==== Ex 4 :Number of times a publication by a specific author is cited
# 
# COUNT 
#   ?protein
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :citation ?citation] AND 
#   [?citation :author "Bairoch A."] 
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf

# No COUNT in SPARQL

PREFIX :     <urn:lsid:uniprot.org:ontology:>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?protein 
WHERE 
{
   ?protein rdf:type :Protein ;
           :citation [ :author "Bairoch A." ] .
}
