PREFIX :     <urn:lsid:uniprot.org:ontology:>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?protein 
WHERE 
{
   ?protein :citation [ :author "Bairoch A." ] .
   ?protein rdf:type :Protein .
}