PREFIX  rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :      <urn:lsid:uniprot.org:ontology:>
SELECT  ?related
WHERE
{
    ?protein  :classifiedWith  <urn:lsid:uniprot.org:keywords:48> .
    ?protein  rdf:type         :Protein .
    ?protein  rdfs:seeAlso     ?related .
  }
