# ==== Ex 8 : Recently modified entries
# 
# SELECT 
#   ?protein, ?date
# WHERE 
#   [?protein rdf:type :Protein] AND 
#   [?protein :modified ?date] AND 
#   ?date > "2004-08"
# USING 
#   "urn:lsid:uniprot.org:ontology:",
#   "http://www.w3.org/1999/02/22-rdf-syntax-ns#" AS rdf

PREFIX  rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  :      <urn:lsid:uniprot.org:ontology:>
SELECT  ?protein ?date
WHERE
  { ?protein  rdf:type   :Protein ;
              :modified  ?date .
    # Not a date!
    FILTER ( ?date > "2004-08" )
  }
