/* Generated By:JavaCC: Do not edit this line. SSE_ParserConstants.java */
/*
 * (c) Copyright 2006 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package sse.parser ;

public interface SSE_ParserConstants {

  int EOF = 0;
  int WS = 6;
  int SINGLE_LINE_COMMENT = 7;
  int Q_IRIref = 8;
  int QNAME = 9;
  int BLANK_NODE_LABEL = 10;
  int VAR1 = 11;
  int VAR2 = 12;
  int LANGTAG = 13;
  int A2Z = 14;
  int A2ZN = 15;
  int DIGITS = 16;
  int INTEGER = 17;
  int DECIMAL = 18;
  int DOUBLE = 19;
  int EXPONENT = 20;
  int QUOTE_3D = 21;
  int QUOTE_3S = 22;
  int ECHAR = 23;
  int STRING_LITERAL1 = 24;
  int STRING_LITERAL2 = 25;
  int STRING_LITERAL_LONG1 = 26;
  int STRING_LITERAL_LONG2 = 27;
  int LPAREN = 28;
  int RPAREN = 29;
  int LBRACE = 30;
  int RBRACE = 31;
  int LBRACKET = 32;
  int RBRACKET = 33;
  int DATATYPE = 34;
  int AT = 35;
  int HOOK = 36;
  int NCCHAR1P = 37;
  int NCCHAR1 = 38;
  int NCCHAR = 39;
  int NCNAME_PREFIX = 40;
  int NCNAME = 41;
  int VARNAME = 42;
  int WORD = 43;
  int OP = 44;
  int UNKNOWN = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<Q_IRIref>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"^^\"",
    "\"@\"",
    "\"?\"",
    "<NCCHAR1P>",
    "<NCCHAR1>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<VARNAME>",
    "<WORD>",
    "<OP>",
    "<UNKNOWN>",
  };

}
