#!/bin/bash
# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

if [ "$TDBROOT" = "" ]
then
    echo "TDBROOT is not set" 1>&2
    exit 1
    fi

"$TDBROOT/bin-test/driver"  exthash "$@"
