#!/bin/bash

export FUSEKIROOT="$PWD"

BACKGROUND=${BACKGROUND:-1}
if [ "$BACKGROUND" = 0 ]
then
    LOGCONFIG=${LOGCONFIG:-file:log4j-foreground.properties}
else
    LOGCONFIG=${LOGCONFIG:-file:log4j-server.properties}
fi

LOG1="-Dlog4j.configuration=${LOGCONFIG}"
LOG2="-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger"
export FUSEKI_LOG="$LOG1 $LOG2"

if [ "$BACKGROUND" = 0 ]
then
    # Run in the foreground
    exec fuseki --pages=demo-pages --config config.ttl
else
    # Run in the background
    # Linux / nohup
    nohup fuseki --pages=demo-pages --config config.ttl > nohup.log 2>&1 &
    # Process ID ... of the script.
    ## PROC=$!
    ## echo "Server process = $PROC"
fi
