PREFIX : <http://example/>

SELECT *
{
  { ?X :name "paul" .
    ?Y :name "george" .
    OPTIONAL { ?X :email ?Z }
  }
UNION
  {
    ?Y :name "george" .
    OPTIONAL { ?X :email ?Z }
    ?X :name "paul" .
  }
}