PREFIX : <http://example/>

SELECT *
{
  {
    { ?X :name ?Y .
      OPTIONAL { ?X :email ?E }
    }
    ?X :phone "888-4537" .
  }
  UNION
  {
    { ?X :name ?Y .
      ?X :phone "888-4537" .
    }
    OPTIONAL { ?X :email ?E }
  }
}