// $ANTLR : "c:/home/afs/Projects/Jena2/src/com/hp/hpl/jena/n3/n3.g" -> "N3AntlrParser.java"$

package com.hp.hpl.jena.n3 ;
import java.io.* ;
import antlr.TokenStreamRecognitionException ;

public interface N3AntlrParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ANON = 4;
	int FORMULA = 5;
	int QNAME = 6;
	int KEYWORD = 7;
	int NAME_OP = 8;
	int KW_THIS = 9;
	int KW_OF = 10;
	int KW_HAS = 11;
	int KW_A = 12;
	int KW_IS = 13;
	int AT_PREFIX = 14;
	int AT_LANG = 15;
	int STRING = 16;
	int LITERAL = 17;
	int SEP = 18;
	int SEMI = 19;
	int COMMA = 20;
	int PATH = 21;
	int RPATH = 22;
	int EQUAL = 23;
	int ARROW_R = 24;
	int ARROW_L = 25;
	int ARROW_P_L = 26;
	int ARROW_P_R = 27;
	int LBRACK = 28;
	int RBRACK = 29;
	int LCURLY = 30;
	int RCURLY = 31;
	int LPAREN = 32;
	int RPAREN = 33;
	int DATATYPE = 34;
	int URIREF = 35;
	int UVAR = 36;
	int QNAME_OR_KEYWORD_OR_NAME_OP = 37;
	int URI_OR_IMPLIES = 38;
	int URICHAR = 39;
	int AT_WORD = 40;
	int AT = 41;
	int NAME_IT = 42;
	int QUESTION = 43;
	int ARROW_MEANS = 44;
	int COLON = 45;
	int SL_COMMENT = 46;
	int NL1 = 47;
	int NL2 = 48;
	int NL3 = 49;
	int NL = 50;
	int WS = 51;
	int ALPHA = 52;
	int ALPHANUMERIC = 53;
	int NON_ANC = 54;
	int NSNAME = 55;
	int LNAME = 56;
	int STRING1 = 57;
	int STRING2 = 58;
	int QUOTE3S = 59;
	int QUOTE3D = 60;
	int ESCAPE = 61;
	int ESC_CHAR = 62;
}
