// $ANTLR : "c:/home/afs/Projects/Jena2/src/com/hp/hpl/jena/n3/n3.g" -> "N3AntlrParser.java"$

package com.hp.hpl.jena.n3 ;
//import java.io.* ;
//import antlr.TokenStreamRecognitionException ;

public interface N3AntlrParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ANON = 4;
	int FORMULA = 5;
	int QNAME = 6;
	int KEYWORD = 7;
	int NAME_OP = 8;
	int KW_THIS = 9;
	int KW_OF = 10;
	int KW_HAS = 11;
	int KW_A = 12;
	int KW_IS = 13;
	int TK_LIST = 14;
	int TK_LIST_FIRST = 15;
	int TK_LIST_REST = 16;
	int TK_LIST_NIL = 17;
	int AT_PREFIX = 18;
	int AT_LANG = 19;
	int STRING = 20;
	int LITERAL = 21;
	int SEP = 22;
	int SEMI = 23;
	int COMMA = 24;
	int PATH = 25;
	int RPATH = 26;
	int EQUAL = 27;
	int ARROW_R = 28;
	int ARROW_L = 29;
	int ARROW_PATH_L = 30;
	int ARROW_PATH_R = 31;
	int LBRACK = 32;
	int RBRACK = 33;
	int LCURLY = 34;
	int RCURLY = 35;
	int LPAREN = 36;
	int RPAREN = 37;
	int DATATYPE = 38;
	int URIREF = 39;
	int UVAR = 40;
	int QNAME_OR_KEYWORD_OR_NAME_OP = 41;
	int URI_OR_IMPLIES = 42;
	int URICHAR = 43;
	int AT_WORD = 44;
	int AT = 45;
	int NAME_IT = 46;
	int QUESTION = 47;
	int ARROW_MEANS = 48;
	int COLON = 49;
	int SL_COMMENT = 50;
	int NL1 = 51;
	int NL2 = 52;
	int NL3 = 53;
	int NL = 54;
	int WS = 55;
	int ALPHA = 56;
	int ALPHANUMERIC = 57;
	int NON_ANC = 58;
	int NSNAME = 59;
	int LNAME = 60;
	int STRING1 = 61;
	int STRING2 = 62;
	int QUOTE3S = 63;
	int QUOTE3D = 64;
	int ESCAPE = 65;
	int ESC_CHAR = 66;
}
