version: '3'

services:
  # ZooKeeper for coordination
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data
      - zookeeper-logs:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - delta-network

  # Primary RDF Delta server
  delta-server-1:
    build: .
    ports:
      - "1066:1066"
    depends_on:
      - zookeeper
    volumes:
      - delta-data-1:/var/lib/delta-server
    environment:
      DELTA_SERVER_PORT: 1066
      DELTA_STORAGE_PATH: /var/lib/delta-server/store
      DELTA_CLUSTER_ENABLED: "true"
      DELTA_CLUSTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      DELTA_METRICS_ENABLED: "true"
      JAVA_OPTS: "-Xmx1g"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1066/$/list"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - delta-network

  # Secondary RDF Delta server for high availability
  delta-server-2:
    build: .
    ports:
      - "1067:1066"
    depends_on:
      - zookeeper
    volumes:
      - delta-data-2:/var/lib/delta-server
    environment:
      DELTA_SERVER_PORT: 1066
      DELTA_STORAGE_PATH: /var/lib/delta-server/store
      DELTA_CLUSTER_ENABLED: "true"
      DELTA_CLUSTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      DELTA_METRICS_ENABLED: "true"
      JAVA_OPTS: "-Xmx1g"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1066/$/list"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - delta-network

  # Fuseki server with RDF Delta integration
  fuseki:
    image: apache/jena-fuseki
    ports:
      - "3030:3030"
    depends_on:
      - delta-server-1
      - delta-server-2
    volumes:
      - fuseki-data:/fuseki
    environment:
      FUSEKI_BASE: /fuseki
      JVM_ARGS: "-Xmx2g"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - delta-network

  # Load balancer for RDF Delta servers
  haproxy:
    image: haproxy:2.5
    ports:
      - "8066:8066"
    depends_on:
      - delta-server-1
      - delta-server-2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    networks:
      - delta-network

volumes:
  zookeeper-data:
  zookeeper-logs:
  delta-data-1:
  delta-data-2:
  fuseki-data:

networks:
  delta-network:
    driver: bridge