#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
echo "Grammar output in sparql-grammar.html"

##jj2html 'sparql_11.txt' 'tokens.txt' > X11.html
##grammarExtracts < X11.html > Y11.html

(
    echo "        <!-- GRAMMAR -->"
    jj2html 'sparql_12.txt' 'tokens.txt'
    echo "        <!-- GRAMMAR -->"
) > sparql-grammar.html

## Produce a standlone web page
## mv sparql-grammar.html X12.hmtl
## grammarExtracts < sparql-grammar.html > sparql-html.html

## jj2html 'arq_12.txt' 'tokens.txt' > X.html
## grammarExtracts < X.html > Y.html
