PREFIX  foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX  vCard:  <http://www.w3.org/2001/vcard-rdf/3.0#>

SELECT ?name1 ?name2
WHERE
{
  ?x a foaf:Person
    OPTIONAL { ?x foaf:name ?name1 } 
    OPTIONAL { ?x vCard:FN  ?name2 }
}
