PREFIX   :      <http://example/>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xsd:    <http://www.w3.org/2001/XMLSchema#>

# No matches

SELECT ?v
WHERE { ?x :p ?v . FILTER ( ?v = "aaa" ) }
