PREFIX  xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX  :       <http://example/>
PREFIX  ex:     <http://example/ns#>

# 1 Optional, later inner join.
# (Preparetion for next test)

SELECT *
{
   ?x :p ?z  
   OPTIONAL { ?z :q1 ?w }
   ?x :p2 ?z

}