vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|04 Sep 2005 15:32:31 -0000
vti_extenderversion:SR|6.0.2.6353
vti_cacheddtm:TX|04 Sep 2005 15:32:31 -0000
vti_filesize:IR|161
vti_backlinkinfo:VX|Tutorial/basic_patterns.html
